### ISSUE TITLE
Als gebruiker wil ik kunnen zoeken in OpenCatalogi

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#1]
Uitvraag *OpenCatalogi valt of staat met een volwassen zoekfunctionalteit. Het is mogelijk dat deze functie door een ander component dan binnen OpenCatalogi wordt gerealiseerd. Naadloze integratie is in dit geval wel een vereiste*

Taken
- #141

Acceptatie Criteria

- [x] Als gebruiker kan ik naar OpenCatalogi.nl gaan
- [x] Als gebruiker kan in een zoekveld een zoekwoord of deel daarvan opgeven
- [x] Als gebruiker krijg ik overzicht gepresenteerd van componenten die aan dit criterium voldoen
- [x] Als gebruiker kan ik het type opgeven het type component waarop ik zoek Component, Applicatie, Datamodel, Proces.

**Comment by bbrands02** [comment]
Het type kunnen we kwijt in nl.commonground.layerType. Dit moeten we nog testen en testdata voor maken

**Comment by bbrands02** [comment]
Dit zijn de enum waardes in de api op stoplight: 

![Image](https://user-images.githubusercontent.com/57346398/177994061-69e71c11-a6d3-4e77-b427-9c38c1012a6e.png)

**Comment by matthiasoliveiro** [comment]
Zie onderstaand voorstel

![Image](https://user-images.githubusercontent.com/36506861/178267375-37ebd625-ec80-4059-8f4a-ec94901aec9b.png)

**Comment by lencodes** [comment]
@bbrands02 ik assign deze aan jou doordat de data nog niet beschikbaar is om deze filtering te maken. Meer informatie kan je vinden in [#19](https://github.com/OpenCatalogi/.github/issues/19).

**Comment by lencodes** [comment]
Overige backend configuration is opgenomen in #163, daarom sluit ik dit issue.

**Comment by RonaldvCortenberghe** [comment]
done

**Comment by RonaldvCortenberghe** [comment]
done
