### ISSUE TITLE
Interface afhankelijk maken van de huisstijl

### ISSUE THREAD

**Issue by RonaldvCortenberghe** [OpenCatalogi/.github#102]
### Project Location

Frontend

### Is your feature request related to a problem? Please describe

Als gemeente wil ik de applicatie in kunnen richten met de gemeentelijke huisstijl, denk hierbij aan kleurstellingen, logo en dergelijke

### Describe the solution you'd like

Het is wenselijk dat er een deel is waarin de configuratie aan gepast kan worden

### Describe alternatives you've considered

niet aanpassen aan huisstijl

### Additional context

Acceptatie criteria:

- [ ] In het kader van NL-Design moet de front-end van huisstijl kunnen switchen.

**Comment by rubenvdlinde** [comment]
Dat betekend dus dat de huisstijl configureerbaar moet zijn op installatie niveau, ofwel via helm. Concreet komt dat er op neer dat er een .env variabele moet worden gepasseerd aan de front-end die bepaald welke token zet er wordt geladen met betrekking tot nL-Design.

**Comment by lencodes** [comment]
@rjzondervan Ik heb vandaag een theme switcher gebouwd in de frontend, hierdoor kunnen we nu dynamisch de `.css` bestanden updaten.

Dit betekent dat dit issue in de frontend klaar staat en dat we enkel nog vanuit de backend moeten meekrijgen wélke implementatie we op dit moment draaien (en dus welk thema we kunnen inladen).

Ik assign daarom dit issue aan jou.

**Comment by lencodes** [comment]
@rjzondervan ik denk dat het thema het makkelijkste in de `env` geschreven kan worden. In de huidige variant van dit project kan dit echter nog niet (we maken nu gebruik van de _oude_ `env.js` setup). In [deze pull request](https://github.com/ConductionNL/skeleton-pip/pull/71) hebben we hier een oplossing voor gevonden (in `skeleton-pip`).

Ik stel voor om samen even 30-60min te pakken op dit te pair-programmen.
