### ISSUE TITLE
Als gebruiker wil ik een organisatie detail pagina

### ISSUE THREAD

**Issue by lencodes** [OpenCatalogi/.github#108]
@RonaldvCortenberghe in #71 wordt gerefereerd naar een organisatie detail pagina. Hier hebben we echter nog geen specificaties voor refined (denk ik).

**Comment by rubenvdlinde** [comment]
De dataset geeft hier op zich wel een aardig antwoord op doh, een organisatie kent een aantal verbanden tot componenten. Dat betekend dat je simpelweg algemene organisatie gegevens kan weergeven. En dan vervolgens de verbanden tot componenten.

e.g. gebruik ...... beheerd ...... is eigenaar van ..... beid ondersteuning op ......
