### ISSUE TITLE
Task: gateway koppelen aan frontend en testdata implementeren

### ISSUE THREAD

**Issue by lencodes** [OpenCatalogi/.github#110]
Momenteel is de koppeling naar de Gateway beschikbaar, maar nog niet geïmplementeerd en wordt er test data ingeladen via een lokaal JSON bestand.

Acceptatie:

- [x] De data wordt ingeladen vanuit de Gateway;
- [x] De data wordt cached d.m.v. React Query;
- [x] De data wordt pre-loaded;
- [x] De changes staan op `development`

**Comment by RonaldvCortenberghe** [comment]
done
