### ISSUE TITLE
(GEDEELTELIJK) Visualisatie : Google search #57

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#112]
Referentie: [https://github.com/OpenCatalogi/.github/issues/57#:~:text=Ik%20wil%20de%20zoekresultaten%20kunnen%20weergeven%20als%20cards%2C%20tabel%20of%20lagen%20(aan%20de%20hand%20van%20resultaat%20icoontjes)|https://github.com/OpenCatalogi/.github/issues/57#:~:text=Ik%20wil%20de%20zoekresultaten%20kunnen%20weergeven%20als%20cards%2C%20tabel%20of%20lagen%20(aan%20de%20hand%20van%20resultaat%20icoontjes)|smart-link]

**Comment by MWest2020** [comment]
gerefereerde issue gesloten
