### ISSUE TITLE
Als gebruiker wil ik kunnen zoeken in OpenCatalogi #1

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#113]
* [https://github.com/OpenCatalogi/.github/issues/1|https://github.com/OpenCatalogi/.github/issues/1|smart-link] 
* [https://github.com/OpenCatalogi/.github/issues/71|https://github.com/OpenCatalogi/.github/issues/71|smart-link] 
* [https://github.com/OpenCatalogi/.github/issues/72|https://github.com/OpenCatalogi/.github/issues/72|smart-link] 
* [https://github.com/OpenCatalogi/.github/issues/75|https://github.com/OpenCatalogi/.github/issues/75]
* [https://github.com/OpenCatalogi/.github/issues/73|https://github.com/OpenCatalogi/.github/issues/73]
* [https://github.com/OpenCatalogi/.github/issues/76|https://github.com/OpenCatalogi/.github/issues/76]
* [https://github.com/OpenCatalogi/.github/issues/74|https://github.com/OpenCatalogi/.github/issues/74]

**Comment by MWest2020** [comment]
alle gerelateerde issues zijn gesloten en de zoekfunctie is in OC
