### ISSUE TITLE
Als gebruiker wil ik een landingspagina #19

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#117]
Een searchbar, het invoeren van een zoekterm zet meteen door naar de componenten overzichtspagina

[https://github.com/OpenCatalogi/.github/issues/19|https://github.com/OpenCatalogi/.github/issues/19|smart-link]

**Comment by MWest2020** [comment]
gerelateerde issue gesloten en zoekbalk is er
