### ISSUE TITLE
Mogelijkheid tot "Uitgebreid zoeken"

### ISSUE THREAD

**Issue by RonaldvCortenberghe** [OpenCatalogi/.github#121]
### Project Location

Somewhere else (please specify in the description!)

### Is your feature request related to a problem? Please describe

Als gebruiker
wil ik naast de filtering op de gedefinieerde velden (bijv GEMMA objecten) ook "uitgebreid zoeken" mogelijkheden hebben
zodat we flexibeler zijn bij list-of-values velden en ze bijvoorbeeld kunnen groeperen en gedeeltelijk zoeken zoals bij overheid.nl
 zie https://open.overheid.nl/uitgebreid-zoeken

### Describe the solution you'd like

zie https://open.overheid.nl/uitgebreid-zoeken

### Describe alternatives you've considered

none

**Comment by MWest2020** [comment]
De huidige zoekfuncite is uitgebreider dan de voorgesteld open.overheid
