### ISSUE TITLE
Task: UPL objecten lijst met uuid's

### ISSUE THREAD

**Issue by bbrands02** [OpenCatalogi/.github#129]
Lijst: https://standaarden.overheid.nl/owms/oquery/UPL-actueel.json

Deze lijst moet gesynchroniseerd worden. 

Voorbeeld object:
{
  "id": uuid,
  "name": UniformeProductnaam.value,
  "grondslagLabel": Grondslaglabel.value
]

**Comment by rubenvdlinde** [comment]
Wilco Louwerse commented: [https://github.com/OpenCatalogi/.github/issues/129|https://github.com/OpenCatalogi/.github/issues/129|smart-link]

**Comment by WilcoLouwerse** [comment]
Sync (na eerste keer inladen) is voor nu out of scope:
![Image](https://user-images.githubusercontent.com/3785488/179714932-49618d23-4ff1-482e-b71b-056227db274a.png)

**Comment by rubenvdlinde** [comment]
Done
