### ISSUE TITLE
Task: Organization object

### ISSUE THREAD

**Issue by bbrands02** [OpenCatalogi/.github#130]
Deze is nodig om op organisaties te filteren, er moet een endpoint zijn om organisaties op te halen zodat deze in de frontend gebruikt kunnen worden in een select. Ook is het nodig voor toekomstige issues over organisatie detail pagina's. Momenteel hebben we alleen een name nodig (die unique moet zijn, kan aangegeven worden via gateway config Attribute.mustBeUnique) en kan dit object later uitgebreid worden. Het object Component zijn legal.repoOwner zou hier aan gekoppeld moeten worden.

**Comment by lencodes** [comment]
@rubenvdlinde ik heb begrepen dat hier gewacht wordt op een voorstel.

**Comment by rubenvdlinde** [comment]
Ruben van der Linde commented: [~accountid:61dbf1819ee70a0068af7209] dat klopt

**Comment by rubenvdlinde** [comment]
Ruben van der Linde commented: Organisation object is toegevoegd aan stoplight, met eigen endpoint. Daarnaas is op de usedBy en contractor properties van commponent het gebruik van dit organisation object toegevoegd

**Comment by rubenvdlinde** [comment]
Object moet nog wel gebruikt worden op de organisatie pagina
