### ISSUE TITLE
Task: Endpoint toevoegen waar op meerdere entiteiten tegelijk gezocht kan worden

### ISSUE THREAD

**Issue by bbrands02** [OpenCatalogi/.github#132]
Hier moet nog over nagedacht worden wat de mooiste oplossing is.

**Comment by WilcoLouwerse** [comment]
Zie: https://github.com/OpenCatalogi/.github/issues/18

**Comment by WilcoLouwerse** [comment]
Om tijd te besparen is besloten voor nu de volgende oplossing hiervoor toe te passen:
Een nieuw endpoint toevoegen en instellen op welke entiteiten gezocht mag worden door deze aan het endpoint vast te maken met een relatie.
Dan ergens in de gateway afvangen wanneer er een get collectie word gedaan op een endpoint met meerdere entiteiten waar op gezocht mag worden. En waarna we dan gefiltered resultaat terug geven.

(In de toekomst op de gateway hier anders mee omgaan, een los object toevoegen hiervoor maybe?)

**Comment by rubenvdlinde** [comment]
Euh nou dit zou ik zeker niet hacky tacky doen. Denk dat er hier twee routes zijn

1. Een regulier endpoint waarbij in meerdere entiteiten kan worden gezocht (dat moet dan wel weer mapping op zijn etc etc) bijvoorbeeld een BSN nummer staat niet in iedere entiteit op dezelfde plek
2.  Een GraphQL endpoint beginnen op te bouwden op /query (deze zit er al een tijdje aan te komen) zodat daar lijstjes van whatever kunnen worden opgehaald. 

Het bouwen van een graphql endpoint vraagt er echter om dat we graphql gaan mappen op doctrine, dat vraag om zijn beurt weer om het afbouwen van het database project waar Robert mee bezig was. Dus stevige impendement.

In een bredere context zie ik overigens nog niet wat de noodzaak van één endpoint binnen dit project. Het is an zich ook prima als er meerdere endpoints voor de verschillende lijstjes zijn.

**Comment by rubenvdlinde** [comment]
Done
