### ISSUE TITLE
Task: QueryParameter object aanmaken voor uitgebreid filteren op properties van een object

### ISSUE THREAD

**Issue by bbrands02** [OpenCatalogi/.github#133]
Zodat er '' of '' of '' of gefiltered kan worden ipv '' en  '' en ''

**Comment by WilcoLouwerse** [comment]
Zie: https://github.com/OpenCatalogi/.github/issues/18

**Comment by rubenvdlinde** [comment]
Kan iemand mij hier nog een keer doorheen nemen? Want ik ervaar de noodzaak eigenlijk nog steeds niet?

**Comment by rubenvdlinde** [comment]
Done
