### ISSUE TITLE
Als developer wil ik een implementatie van @context

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#138]
Zodat ik informatie over objecten kan ophalen. zie ook

[https://en.wikipedia.org/wiki/JSON-LD|https://en.wikipedia.org/wiki/JSON-LD|smart-link] 
[https://niem.github.io/json/reference/json-ld/context/|https://niem.github.io/json/reference/json-ld/context/|smart-link] 
[https://developer.openactive.io/data-model/context-and-json-ld|https://developer.openactive.io/data-model/context-and-json-ld|smart-link] 
[https://data.letsride.co.uk/opendata/britishcycling.jsonld|https://data.letsride.co.uk/opendata/britishcycling.jsonld] 
[https://www.w3.org/RDF/|https://www.w3.org/RDF/|smart-link]

**Comment by RonaldvCortenberghe** [comment]
status?

**Comment by RonaldvCortenberghe** [comment]
Ik heb geen concrete userstories vanuit de business die een financiering kunnen opleveren
