### ISSUE TITLE
Als eindgebruiker van OpenCatalogi wil ik een heldere definitie van Applicaties en Componenten, zodat...

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#139]
Niet meegekomen in de sync (denk ik). Refereert naar: [https://github.com/OpenCatalogi/.github/issues/93|https://github.com/OpenCatalogi/.github/issues/93|smart-link]

**Comment by MWest2020** [comment]
gerelateerde issue gesloten
