### ISSUE TITLE
Bug: nl.gemma en nl.commonground moet extended en op gefiltered kunnen worden

### ISSUE THREAD

**Issue by bbrands02** [OpenCatalogi/.github#140]
Deze gegevens kunnen niet worden extended omdat het subobjecten in subobjecten zijn. Het lijkt er op dat de OASparser hier niet goed mee om kan gaan.

Omdat het aanpassen van het schema om dit issue te quick-fixen een afwijking zou zijn op de publiccode standaard heeft het de voorkeur om dit op te lossen door de OASparser op dit punt te repareren zodat de gegevens correct kunnen worden geëxtend.

Hierin is dus het stappenplan:
- [x] Uitzoeken wat er precies mis gaat
- [x] Waarom gaat dit mis?
- [x] Hoe los ik dit op?

**Comment by WilcoLouwerse** [comment]
Extend bug is opgelost en staat op de feature-cleanup branch

**Comment by WilcoLouwerse** [comment]
Bug is opgelost op de online omgeving
