### ISSUE TITLE
Task: top-nav link icons toevoegen en underline weghalen

### ISSUE THREAD

**Issue by lencodes** [OpenCatalogi/.github#143]
Top navigatie mag geüpdatet worden:

- [x] Alle items mogen een icon krijgen;
- [x] Alle underlines mogen verwijderd worden;
- [x] ~~Een documentatie item mag toegevoegd worden (linken naar interne pagina, mag een lege pagina zijn)~~ Deze gaat naar de main navigatie als drop-down.

**Comment by lencodes** [comment]
NL Design heeft geen icon, dus voor deze heb ik een `External` icon gebruikt. Andere icons heb ik weten te converteren naar `svg`, zie screenshot:



![Image](https://user-images.githubusercontent.com/66552932/180978044-59b895b2-ca2d-44ba-8594-bce37df7c855.png)

**Comment by RonaldvCortenberghe** [comment]
done
