### ISSUE TITLE
Task: homepage mini-dashboard

### ISSUE THREAD

**Issue by lencodes** [OpenCatalogi/.github#144]
Onder de zoekbalk op de home pagina mag een "mini dashboard" komen. Het dashboard zijn blokken met de nav items (excl. _Home_).

In de blokken staan de titels van de items en de count van de items.

Dat betekent in de huidige versie:

- [x] Software
- [x] Datamodellen
- [x] API's

**Comment by lencodes** [comment]
Zie onderste deel van screenshot:



![Image](https://user-images.githubusercontent.com/66552932/180790212-95e2587f-7ef9-4948-bed8-2e5f5103c4d2.png)

**Comment by rubenvdlinde** [comment]
done
