### ISSUE TITLE
Bug: Bij 3 calls tegelijk kunnen results leeg terugkomen

### ISSUE THREAD

**Issue by bbrands02** [OpenCatalogi/.github#149]
Als er vanuit de frontend tegelijk /v1/referentielijsten/upl, v1/referentielijsten/licenses en v1/referentielijsten/bedrijfsservices opgehaald hebben 2 van de 3 requests meestal een leeg result. Er zou in de gateway gevardumpt moeten worden om te achterhalen waarom dit gebeurd

**Comment by rubenvdlinde** [comment]
Dit wordt evt afgedekt door de implementatie van elastick search
