### ISSUE TITLE
Task: select element population via gateway inladen

### ISSUE THREAD

**Issue by lencodes** [OpenCatalogi/.github#150]
Momenteel worden de select velden (zie lijst hieronder) gevuld via data in de frontend, deze data moet via de gateway gaan verlopen.

- [x] UPL;
- [x] Organisatie;
- [x] Licentie en
- [x] GEMMA (bedrijfsfuncties, bedrijfsservices, referentie componenten en applicatiefuncties).

Dit issue is blocked door #149.

**Comment by rjzondervan** [comment]
@rubenvdlinde wat is het effect van het gebruik van elasticsearch op dit issue?

**Comment by rubenvdlinde** [comment]
Data gaan we opnemen inreferentie lijsten
