### ISSUE TITLE
Task: array filters doorsturen en testen met de gateway

### ISSUE THREAD

**Issue by lencodes** [OpenCatalogi/.github#151]
Momenteel stuurt de front de array filters (lagen, platforms, UPL, bedrijfsfuncties, bedrijfsservices en referentie componenten) door naar de gateway, maar werkt de filtering niet.

- [ ] De filters zijn getest en werken naar verwachting.

~~Dit issue is blocked door: #142.~~

**Comment by remko48** [comment]
Dit issue is niet meer blocked door: #142.
Er is getest en alle filters op één na doen het naar verwachting.

**Comment by rubenvdlinde** [comment]
Done
