### ISSUE TITLE
Task: proces toevoegen aan main-navigation

### ISSUE THREAD

**Issue by lencodes** [OpenCatalogi/.github#152]
De main-navigatie mag een item "Processen" krijgen, wanneer hier naartoe genavigeerd wordt moet er een filter actief gezet worden. 

Het filter haakt in op `softwareType`.

- [ ] Menu item is beschikbaar 
- [ ] De filtering werkt.

~~Dit issue is blocked door: #141.~~

**Comment by lencodes** [comment]
`process` is nu beschikbaar in `softwareType` en dit issue is dus niet meer blocked.

**Comment by RonaldvCortenberghe** [comment]
done
