### ISSUE TITLE
Task: component detailpagina tabbladen data inladen

### ISSUE THREAD

**Issue by lencodes** [OpenCatalogi/.github#153]
De huidige tabbladen (zie screenshot) bevatten dummy data, deze data mag vanuit de Gateway ingeladen gaan worden.

Let op: het is (nog) niet volledig duidelijk welke data in welk tabblad mag komen, dit is onderdeel van deze task.

- [x] Componenten;
- [x] Afhankelijkheden;
- [x] Standaarden;
- [x] Leveranciers;
- [x] Hergebruik;
- [x] Schema's;
- [x] Processen;
- [x] Producten;

**Comment by rubenvdlinde** [comment]
Stapje terug, er moet even wat meer holistisch naar de "Component" pagina worden gekeken. Niet alle data hoeft namenlijk in een tabblad. En sommige data is hetzelfde (componenten en afhankelijkheden bijvoorbeeld)

**Comment by lencodes** [comment]
> Stapje terug, er moet even wat meer holistisch naar de "Component" pagina worden gekeken. Niet alle data hoeft namenlijk in een tabblad. En sommige data is hetzelfde (componenten en afhankelijkheden bijvoorbeeld)

@rubenvdlinde Het doel van deze taak is niet _hoe_ we het gaan vormgeven en presenteren (e.g. in een tabblad of op een andere wijze). Het gaat hier enkel om wélke data hebben we en welke data willen we tonen. 

Vormgeving en presentatie wordt pas opgepakt in de volgende sprint.

**Comment by remko48** [comment]
@rubenvdlinde

Ik heb onderzocht welke stukken data vanuit de Gateway we op welke tabbladen kan komen te staan hiervoor heb ik de OAS en documentatie gebruikt en daar zijn wat vragen en voorstellen uit gekomen:

- Afhankelijkheden/Componenten: Hiervoor kan de data gebruikt worden vanuit "dependsOn". Volgens mij is het ook mogelijk dat er geen data staat in de velden van "dependsOn", ("open","proprietary","hardware") zijn deze velden nullable?

- Leveranciers: Er is geen specifiek veld voor leveranciers, maar in "maintainers" staat een veld genaamd "contactors" dit veld lijkt voor mij het meest op leveranciers. Kan dit veld gebruikt worden als leveranciers?

- Hergebruik: Ik stel voor om voor het tabblad Hergebruik de data uit het veld "usedBy" te gebruiken. In deze data staat welke bedrijven het component gebruiken, dit klinkt voor mij als hergebruik.

- Standaarden: Komt de data voor standaarden in de velden van "gemma" te staan? Zo nee waar zou de data voor standaarden dan komen te staan?

- Processen/Schema's: Ik kon alleen een verwijzing naar Processen en Schema's vinden als values in het veld "softwareType". Willen we de data uit dit veld hier voor gebruiken of moeten er nog extra velden komen voor processen en schema's

- Producten: Ik heb hier geen data kunnen vinden die hierbij lijkt te horen. Welk dataveld kan hiervoor gebruikt worden?

**Comment by rubenvdlinde** [comment]
@remko48 

- ja depends on kunnen leeg zijn of zelfs uberhaupt niet voorkomen
- ja dat is voor nu even de oplossing (op termijn gaat die niet vliegen omdat niet elke leverancier zich bij de repro gaat melden)
- ja dat is voor nu even de oplossing (op termijn gaat die niet vliegen omdat niet elke hergebruiker zich bij de repro gaat melden)
- Standaarden moet ik even uitzoeken
- Proccesen of schema's geven zijn dependsOn (het zijn immers zelf ook weer componenten van het type proces of schema)
- Producten zitten uti mijn hoofd in nl.gemma.producten maar die zou ik moeten nazoeken

**Comment by remko48** [comment]
> * Producten zitten uti mijn hoofd in nl.gemma.producten maar die zou ik moeten nazoeken

We hebben nog even gechecked en de data is er als `nl.upl`

**Comment by remko48** [comment]
Versie 1.0 is opgeleverd.
Door ontwikkeling hierop mag in andere issues
