### ISSUE TITLE
Task: gebruik pagina content

### ISSUE THREAD

**Issue by lencodes** [OpenCatalogi/.github#154]
Er is content nodig voor de _Gebruik_ pagina op het platform, content wordt aangeleverd door Gemeente Rotterdam.

- [ ] Content is aangeleverd.

**Comment by rubenvdlinde** [comment]
Kan de gemeente Rotterdam technische documentatie aanleveren dan?

**Comment by rubenvdlinde** [comment]
Begonnen onder -> https://docs.google.com/document/d/1pwserSrtWNuXcGr_6klo66Fwmm9Ecm8iUWixbtSJgOQ/edit#heading=h.eh3n3hcc26r6

**Comment by rjzondervan** [comment]
@rubenvdlinde zou je kunnen inschatten hoe veel werk je hier nog voor nodig hebt?
