### ISSUE TITLE
Als gebruiker wil ik modellen kunnen Downloaden

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#16]
_Alle modellen kunnen worden gedownload, voor datasets geldt het principe bevragen bij de bron_

**Afhankelijk van:**
- Productdetailpagina

**Acties**
- Een download ui component opnemen op de component detailpagina
- Downloads opnemen in de #7 

**Acceptatiecriteria**
- [x] Ik kan op de component detailpagina op downloaden klikken
- [x] Er wordt een pop-up getoond met een waarschuwing betreffende security
- [ ] Het bijbehorende bestand word gedownload

**Comment by RonaldvCortenberghe** [comment]
verder uitwerken van de security aspecten is hier nog nodig

**Comment by rubenvdlinde** [comment]
We defineren een model als een json schema -> https://json-schema.org/ dat is dezelde model definitie en uitwisselings vrm die ook door overige objecten wordt gebruikt.

**Comment by rubenvdlinde** [comment]
Dus voor nu, in fase 1 doen doorlinken ongeacht de bron. Dus mag mooi model zijn maar plaatje is ok prima.
