### ISSUE TITLE
Als developer wil dat collection entity een api prefix krijgt die op alle endpoints toegepast wordt

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#160]
Zodat endpoints niet snel botsen op elkaar zoals 2 /api/organizations endpoints maar bijv /api/oc/organizations

**Comment by rubenvdlinde** [comment]
Barry Brands commented: Bots nu op een subcriber dingetje bij het updaten van de prefix

**Comment by MWest2020** [comment]
is toegevoegd inmiddels
