### ISSUE TITLE
Task: Den Haag en Utrecht components design tokens in thema verwerken

### ISSUE THREAD

**Issue by lencodes** [OpenCatalogi/.github#161]
Momenteel hebben we nog geen overzicht van welke Den Haag en Utrecht componenten (en design tokens) we allemaal geïmplementeerd hebben en kunnen we daardoor deze niet verwerken in het thema.

Lijst van componenten waarvan de design-tokens geïmplementeerd moeten worden: 

- [ ] Heading2
- [ ] Heading3
- [ ] LeadParagraph
- [ ] Button
- [ ] Heading1
- [ ] Link
- [ ] Paragraph
- [ ] Tab
- [ ] TabContext
- [ ] TabPanel
- [ ] Tabs
- [ ] FormField
- [ ] FormFieldInput
- [ ] FormFieldLabel
- [ ] Divider
- [ ] Table
- [ ] TableBody
- [ ] TableCell
- [ ] TableHead
- [ ] TableHeader
- [ ] TableRow

**Comment by lencodes** [comment]
Tokens zijn verwerkt en merged.

**Comment by RonaldvCortenberghe** [comment]
done
