### ISSUE TITLE
Task: Gemeente Rotterdam thema maken

### ISSUE THREAD

**Issue by lencodes** [OpenCatalogi/.github#162]
Er zijn momenteel `--skeleton` tokens én we overschrijven momenteel alle geïmplementeerde componenten met deze tokens. Als volgende stap willen we een Gemeente Rotterdam thema maken wat inhaakt op de tokens.

- [x] Gemeente Rotterdam design token theme bestaat en is geïmplementeerd.

**Comment by lencodes** [comment]
Eerste variant van het Gemeente Rotterdam thema is opgezet, de échte invulling hiervan kunnen we in sprint 3 op door itereren.



![Image](https://user-images.githubusercontent.com/66552932/182595973-5f95ab2b-b19d-4e9c-9193-c50129f1cf04.png)



![Image](https://user-images.githubusercontent.com/66552932/182596030-c2a47837-81e6-4ce9-8ff4-cab3d96219e7.png)



![Image](https://user-images.githubusercontent.com/66552932/182596338-74bfca50-0288-4bc7-aef6-1237deb888aa.png)




Ook hebben we een eerste versie voor het Utrecht thema gemaakt (zodat we het switchen van themas effectief kunnen testen):



![Image](https://user-images.githubusercontent.com/66552932/182596197-360a3263-c04d-486d-99dc-cadeabd539b1.png)



![Image](https://user-images.githubusercontent.com/66552932/182596249-dd90bdb0-f22b-4b91-a90b-7e14b2955cbf.png)



![Image](https://user-images.githubusercontent.com/66552932/182596304-5ad6349d-61fc-424d-bf5e-cdc0b17e30ca.png)

**Comment by RonaldvCortenberghe** [comment]
done
