### ISSUE TITLE
Als gebruiker wil ik een component detail pagina

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#17]
Zodat ik  de gevens van een commponent kan zien

Afhankelijkheden
- #39
- #40

Voorbeelden
- [developer.overheid.nl](https://developer.overheid.nl/apis/00000001802327497000-kadaster-bag-current)
- [componentencatalogus](https://componentencatalogus.commonground.nl/componenten/164?)

Voor de demo gaan we uit van de volgende component data
- Name
- Type
- Description

Naar aanleiding van de huidige commonground componenten catalogus kunnen we trouwens iets meer uitspraken doen over welke informatie er van een component moet worden getoond.

![Componenten Catalogus Component bewerken](https://user-images.githubusercontent.com/4021899/170700919-58cbd323-4d74-4565-a2ec-59dd80d495e7.png)

**Comment by rubenvdlinde** [comment]
Let op we willen hierbij zowiezo dus voor iedere component een net afwijkende pagina

**Comment by lencodes** [comment]
Deze epic is al ingeschat in zijn onderliggende issues.

**Comment by rubenvdlinde** [comment]
Ruben van der Linde commented: !image-20220721-091452.png|width=1056,height=325!

Ik zou UPL hier hernoemen naar producten (dat zegt de gebruiker meer dan UPL). Dan kan dan eventueel een info ballonnetje bij om te vertellen dat het over UPL producten gaat

**Comment by rubenvdlinde** [comment]
Ruben van der Linde commented: !image-20220721-091710.png|width=1042,height=127!

Ik zou het eerste blok gebruiken voor Licentie en daarin of de licentie (als we die weten) of een rood label met een waarschuwing licentie niet gevonden).

In het github veld zou ik een ook een waarschuwing “niet gevonden” tonen als we hem niet hebben.

**Comment by lencodes** [comment]
Er is een eerste opzet voor de detailpagina gemaakt. Hierboven nog feedback ontvangen van @rubenvdlinde; feedback kan (eventueel) in sprint 2 opgepakt worden.

**Comment by RonaldvCortenberghe** [comment]
akkoord
