### ISSUE TITLE
Standaarden mag weg als tabblod op de product pagina

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#171]
!image-20220804-112747.png|width=1368,height=778!

**Comment by MWest2020** [comment]
@rubenvdlinde is dat het stukje gebruikte standaarden of kan dit issue weg?
https://opencatalogi.nl/documentation/about

![image](https://github.com/OpenCatalogi/.github/assets/66728126/8a516ed4-788d-44e3-bb0d-dc66d353847a)
