### ISSUE TITLE
Als gebruiker wil ik een zoekresultatenpagina

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#18]
Zodat ik de gegevens vanuit OpenCatalogi  kan inzien

Grafisch baseren we deze op [developer.overheid code](https://developer.overheid.nl/code?q=nlx&programmingLanguages=5&programmingLanguages=3&programmingLanguages=13). 

De keuze valt primair op de opbouw zo als de code pagina. Dus dubbele filters met (Search bar en Component type) met daaronder cards.

De overzichtspagina heet zoeken en verander nooit van naam
Subtekst = lorum ipsum

Gerelateerde issues
- #1 
- #15

Todo's
- #140  

Acceptatiecriteria
- [ ] Er is een pagina met daar op  cards voor de verschillende componenten 
- [x] De pagina wordt ingeladen met gegevens vanuit de gateway  (voor demo gebruiken we vaste gegevens)
- [ ] Er is een card component voor software
- [ ] Er is een card  component voor processen
- [ ] Er is een card  component voor schema's
- [x] Er is een zoekbalk
- [x] Na een zoekopdracht word de pagina opnieuw ingeladen aan de hand van de zoekopdracht (out of scope voor demo) `FE: 3`
- [x] Er is pagination (out of scope voor demo) `FE: 13`
- [x] Na het klikken op een component card word de #17 geopend
- [ ] Naast een normale grid opbouw voor de cards moet er ook een mogelijkheid zijn om ze te verdelen met over lagen conform #15

**Comment by bbrands02** [comment]
De vraag voor de back-end is: waar en hoe moet er gezocht/gefilterd worden?

**Comment by WilcoLouwerse** [comment]
Afhankelijk van deze epic: (op Conduction Jira Bord) https://conduction.atlassian.net/browse/GW-1196

**Comment by lencodes** [comment]
@RonaldvCortenberghe al deze acceptatiecriteria vallen (voor zover ik zie) onder de visualisatie van de resultaten en passen daardoor beter in sprint 3. Wat denk jij?

> * [ ]  Er is een pagina met daar op  cards voor de verschillende componenten
> * [ ]  Er is een card component voor software
> * [ ]  Er is een card  component voor processen
> * [ ]  Er is een card  component voor schema's
> * [ ]  Naast een normale grid opbouw voor de cards moet er ook een mogelijkheid zijn om ze te verdelen met over lagen conform [Als gebruiker wil ik een visualisatie van componenten op de common ground lagen #15](https://github.com/OpenCatalogi/.github/issues/15)

**Comment by lencodes** [comment]
@bbrands02 ik assign deze aan jou. De `nl.gemma.layerType` mist in de data waardoor we de visualisatie op de layers niet kunnen oppakken.

**Comment by lencodes** [comment]
Overige openstaande backend taken zijn gedocumenteerd in #140, daarom sluit ik dit issue.

**Comment by RonaldvCortenberghe** [comment]
gedaan
