### ISSUE TITLE
Task: Sorteren op meer velden dan datetime (alfabetisch, numeriek)

### ISSUE THREAD

**Issue by WilcoLouwerse** [OpenCatalogi/.github#180]
**Beschrijving:**

Deze task komt oorspronkelijk vanuit dit issue: https://github.com/OpenCatalogi/.github/issues/75

Met de Gateway is het op het moment alleen mogelijk om te sorteren op _dateCreated en _dateModified door een query parameter mee te geven bij een get collectie api call (voorbeeld: ?order[_dateCreated]=desc)

Voor meer informatie over hoe dit nu werkt zie de eavService->handleSearch() functie:
![Image](https://user-images.githubusercontent.com/3785488/183380973-2cc7efe9-252f-4f19-8732-2b7113fe404c.png)
Net zoals voor filteren is er een functie in de objectEntityRepository die kijkt/bepaald waar je wel of niet op mag orderen:
![Image](https://user-images.githubusercontent.com/3785488/183381281-92c5c032-bf17-4b18-8a3e-fc94d402f850.png)
Zoals je hier kunt zien is het nu alleen toegestaan om te orderen op de 2 _date... velden. En is er een begin/voorbeeld aanwezig hoe we ook sorteren op attributen van een Entity kunnen toestaan. (zie ook de getFilterParameters functie als voorbeeld, aangezien deze erg hier op lijkt)

$order word uiteindelijk meegegeven in de eavService aan de objectEntityRepository->findAndCountByEntity() functie:
![Image](https://user-images.githubusercontent.com/3785488/183381691-78beca85-9d96-4571-9ed5-dfa6f16bbc78.png)
Dit is waar de daadwerkelijk dql/sql word gegenereerd voor het zoeken in de db en ordenen van dit zoekresultaat.
De specifieke code voor het orderen staat op 2 plekken (misschien hier ook meteen even 1 functie van maken?). Namelijk in de findAndCountByEntity() functie zelf en in de createQuery() functie.
![Image](https://user-images.githubusercontent.com/3785488/183382425-561440eb-3b41-460c-85c5-bd501f91136c.png)
De getObjectEntityOrder() functie is waar daadwerkelijk orderBy word toegevoegd aan de sql query. $key voor deze functie is waar op georderd word en $value is altijd desc of asc.
![Image](https://user-images.githubusercontent.com/3785488/183391293-51f1f907-6097-4162-a504-30bef672ef36.png)

In deze getObjectEntityOrder() functie zit een switch voor de verschillende velden waar op geordend kan worden. Hier is waar het ingewikkeld word en je dql/sql moet toevoegen om te zorgen dat er ook op velden van een ObjectEntity geordend kan worden. Dus ObjectEntity->objectValues->stringValue. (misschien ook voor datetime en integer velden, deze worden namelijk ook als stringValue opgeslagen, gebruik pgAdmin om even in de db te kijken hoe dit er uit ziet!)
Hierbij raad ik aan om eerst goed te huidige code te bekijken en begrijpen voor het genereren van de sql query (dus alles in objectEntityRepository).
Het kan zijn dat je hiervoor de code van orderen moet verplaatsen of helemaal moet omgooien namelijk.
Zie en begrijp ook vooral de buildQuery() en buildFilterQuery() functies waar in er left joins gedaan worden voor het filteren. Het is belangrijk te begrijpen hoe de ObjectEntities en de values daar onder worden opgeslagen en hoe je deze met een sql query ook netjes terug krijgt of kunt beinvloeden. Ik raad ook sterk aan om eerst even in pgAdmin met sql queries te oefenen om daar eerst voormekaar te krijgen wat je in code wilt toevoegen. (let op, dql is niet 100% gelijk aan sql, dql is meestal wat simpeler, zeker met joins, maar niet altijd)

Het volgende is mijn gevoel en ik weet niet 100% zeker of dit klopt, dit sql verhaal is ingewikkeld ;p 
Ik heb het idee dat als er geen filters worden gebruikt bij de get collectie api-call dat deze left join niet gedaan word:
$query->leftJoin("$objectPrefix.objectValues", $prefix.$filterKey['key']);
($objectPrefix = "o") ($prefix = "value") ($filterKey['key'] staat gelijk aan de key van een filter, dus in het geval van ?name=SomeString zou dit name zijn.)
Deze left join is nodig om op values van een ObjectEntity te kunnen filteren, maar waarschijnlijk ook om er op te kunnen orderen met $prefix.value.$key (waarbij $prefix gelijk is aan "o" en $key gelijk is aan het veld waar je op wilt orderen)

**orderen op subresources** 
(misschien dit in eerste instantie even niet toestaan, dus alleen op het hoofd object en de attributen daarvan, dit is dus te begrenzen door hoe je de getOrderParameters() functie opbouwt. Dan kan je de volgende opmerkingen negeren:)
Ik denk dat we misschien alleen kunnen of zouden moeten kunnen orderen op velden die aanwezig zijn in de query door left joins (dit is vooral relevant als we zouden willen orderen op subresources, dus bijv. van een organization object: "email.name=desc". ipv. gewoon "name=desc".)
Dit heeft te maken met het feit dat als we niet de left joins hebben gedaan voor de subresource we er waarschijnlijk ook niet op kunnen orderen.

**Taken:**
- [x] getOrderParameters() functie uitbreiden zodat orderen op attributen is toegestaan.
- [ ] Code begrijpen en in pgAdmin een sql query maken waarmee je kan filteren op een dateTime attribuut ipv de standaard dateCreated/dateModified.
- [ ] Vorige stap herhalen voor een integer en een string attribuut.
- [ ] Sql queries vanuit pgAdmin omzetten naar code in objectEntityRepository.

**Acceptatiecriteria:**
- [ ] Er kan geordend worden op een datetime attribute van een Entity (/ObjectEntity)
- [ ] Er kan geordend worden op een integer attribute van een Entity (/ObjectEntity)
- [ ] Er kan geordend worden op een string attribute van een Entity (/ObjectEntity)

**Comment by WilcoLouwerse** [comment]
Nog een laatste opmerking:
Wees voorzichtig met meer/nieuwe joins toevoegen, dit is waarschijnlijk ook niet nodig! Hergebruik van bestaande joins door deze bijv. altijd te doen ipv alleen voor filteren is wss the way to go

**Comment by rubenvdlinde** [comment]
Done
