### ISSUE TITLE
Task: test data volledig maken

### ISSUE THREAD

**Issue by lencodes** [OpenCatalogi/.github#181]
De testdata mag verrijkt worden waardoor het volledige object is gevuld (niks `null`).

Dit is eigenlijk een epic die de volgende issues omvat

- [ ] #181 
- [x] #195 
- [x] #195 
- [x] #192

**Comment by rubenvdlinde** [comment]
Ik lees als ik wil dat in de publicode van opencatalogi zelf(dus op github) alle informatie staat zodat ik open catalogi als voorbeeld kan gebruiken
