### ISSUE TITLE
Design & Voorstel: visualisatie zoeken per categorie (homepage)

### ISSUE THREAD

**Issue by lencodes** [OpenCatalogi/.github#182]
We willen vanaf de homepage kunnen zoeken naar componenten per categorie. Een visueel voorbeeld en categorieën is [hier te vinden](https://www.gemmaonline.nl/images/gemmaonline/a/a0/GemeentelijkGegevenslandschap.png).

Notes:

- Per categorie mag een indicator zijn hoeveel componenten erin zitten;

Acceptatiecriteria: 

- [x] ~~Een design is geüpload in dit issue~~; zie onderstaande comments
- [x] ~~Een inschatting is toegevoegd in dit issue~~; eerste versie zonder backend koppeling `8` story points.

**Comment by lencodes** [comment]
Zie onderstaand twee versies van één view. Zoeken per categorie, waarbij de categorieën zijn onderverdeeld in de vijf lagen. 

Doordat we in #183 componenten en applicaties willen onderverdelen in vijf lagen, leek het mij logisch om deze layout te kunnen hergebruiken. En doordat we in #183 logica willen hebben om lagen te kunnen verbergen en tonen, kunnen we deze logica in deze implementatie hergebruiken.

Standaard weergaven (geen filters actief, zo laadt de pagina automatisch):


![Image](https://user-images.githubusercontent.com/66552932/183440194-9080aa10-b355-4025-9d7a-b4df344da4af.jpg)

Gefilterde weergaven (filters actief, gebeurt enkel wanneer een gebruiker één of meerdere lagen uit vinkt):



![Image](https://user-images.githubusercontent.com/66552932/183440301-d410cc38-79d8-498f-896c-0b9e6f65d101.jpg)

**Comment by lencodes** [comment]
Op de accordion-items (de pijltjes achter de titels: interactie, proces, integratie, services en data) updaten de filters en andersom.

**Comment by lencodes** [comment]
In het visuele voorbeeld (zie description van dit issue) zijn iconen per categorie beschikbaar. Deze zouden we kunnen toevoegen, mits deze worden aangeleverd door Rotterdam.

Een andere mogelijke oplossing zou kunnen zijn dat Conduction zelf een set aan iconen inlaadt (we kunnen hierbij soortgelijke iconen zoeken).

**Comment by RonaldvCortenberghe** [comment]
done
