### ISSUE TITLE
Design & Voorstel: visualisatie per laag (component detailpagina)

### ISSUE THREAD

**Issue by lencodes** [OpenCatalogi/.github#183]
We willen in de componenten (of applicatie) detailpagina's een visuele weergave van de bijbehorende componenten (en applicaties) in een 5-lagen visualisatie. [Zie hier een visueel voorbeeld](https://user-images.githubusercontent.com/103419196/182832817-4f9e39bc-ec07-4a6a-aca8-baa13a30cedd.png).

Notes:

- Lagen moeten ingeklapt kunnen worden;
- Op gekoppelde componenten en applicaties moet doorgeklikt kunnen worden.

Acceptatiecriteria:

- [x] ~~Een design is geüpload in dit issue;~~ zie onderstaande comments
- [x] ~~Een inschatting is toegevoegd in dit issue.~~ eerste versie zonder backend koppeling `5` story points; dit is vanuitgaande dat #182 reeds gerealiseerd is.

**Comment by lencodes** [comment]
Voor dit component kunnen we (grotendeels) het component uit #182 hergebruiken. 

Op dezelfde plek als deze view kunnen we ook de "bollenplaat" tonen, hierom is er al een navigatie in toegevoegd ("Lagen" en "Verbanden").

Lagen zonder componenten beschikbaar worden automatisch geminimaliseerd. Lagen mét componenten, hebben de mogelijkheid om geminimaliseerd te worden door de gebruiker.

Hieronder drie designs (voor de verschillende states):

**Standard view**:
![Image](https://user-images.githubusercontent.com/66552932/183605948-9536cff2-3113-4707-82ef-f6a67ec2d5d6.jpg)

**Empty row view**:
![Image](https://user-images.githubusercontent.com/66552932/183606010-b315ba79-fbad-4e99-ade1-d57a6e86a66c.jpg)

**Empty and filtered rows view**:
![Image](https://user-images.githubusercontent.com/66552932/183606065-e173ba69-62b4-42a2-9f46-670092e95239.jpg)

**Comment by RonaldvCortenberghe** [comment]
done
