### ISSUE TITLE
Design & Voorstel: visualisatie met bollen (component detailpagina)

### ISSUE THREAD

**Issue by lencodes** [OpenCatalogi/.github#184]
We willen in de componenten (of applicatie) detailpagina's een visuele weergave van de bijbehorende componenten (en applicaties) in een bollen visualisatie.

Notes:

- Het moet visueel duidelijk zijn welk component (of applicatie) in welke laag zit;
- Op gekoppelde componenten en applicaties moet doorgeklikt kunnen worden.

Acceptatiecriteria:

- [x] ~~Een design is geüpload in dit issue;~~ zie voorbeeld op Dashkube
- [x] ~~Een inschatting is toegevoegd in dit issue.~~ `8`

**Comment by lencodes** [comment]
Update: ik heb vandaag gekeken naar de verschillende mogelijkheden voor deze bollen visualisatie.

Conduction heeft eerder zo'n bollen visualisatie opgeleverd (zie [Dashkube](https://www.dashkube.com/commonground)). Echter kunnen deze bollen niet (makkelijk) `HTML` componenten renderen waardoor we weinig vrijheid hebben in de visualisatie van de bollen zelf.

Note: er kan `HTML` gerenderd worden wanneer we dit wrappen in `svg` componenten, maar ik verwacht dat daar veel problemen bij komen kijken.

Mogelijke andere packages die we kunnen gebruiken (dit moet nog onderzocht worden, deze comment is ter documentatie):

- https://visjs.org/ (origineel)
- https://www.npmjs.com/package/react-vis
- https://observablehq.com/@d3/force-directed-graph
- https://echarts.apache.org/examples/en/editor.html?c=graph-force&lang=ts
- https://echarts.apache.org/examples/en/editor.html?c=graph-label-overlap&lang=ts
- https://www.highcharts.com/demo/network-graph
- https://zoomcharts.com/en/chart-types-demo/bubble-map-mind-map-using-netchart

**Comment by lencodes** [comment]
**Update:**

- We gaan een start maken met `visjs` (die gebruikt wordt op Dashkube), deze package biedt niet alles wat we hoopten, maar we denken toch dat dit de beste oplossing is voor nu;
- We starten met de verbanden tussen het huidige component en zijn `dependsOn` dependencies te tonen (één ring naar buiten; dus geen dependencies van dependencies).

**Comment by RonaldvCortenberghe** [comment]
voorstel klaar task moet nog worden uitgevoerd
