### ISSUE TITLE
Als gebruiker wil ik een landingspagina

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#19]
Zodat ik een opslag kan zien wat open Catalogi mij biedt en wat ik er mee kan doen

Defacto hebben we het hier dus eigenlijk over een landingspagina, zie als voorbeeld \[developer.overheid]([https://developer.overheid.nl/|https://developer.overheid.nl/]). Daarbij zijn tussen rows nice to have

**Impediment** 

* #4 

**Taken**
- #141

**Bestaande uit** 

* \[x] Een Top nav (met als items commonground, haven, nl design en de eigen git repro) `FE: 3`
* \[x] Een header met daarin "Open Catalogi" Als main en "Herbruikbare componenten binnen de overheid" als sub `FE: 3`
* \[x] Een sub menu met daarin "home","Software","Datamodellen","Processen"."Api's","Informatie Modelen" `FE: 3`
* \[x] Dan een main wrapper met als titel ''Een centrale plek voor hergebruik van informatietechnologie binnen de overheid" `FE: 3`
* \[x] Een searchbar, het invoeren van een zoekterm zet meteen door naar de componenten overzichtspagina `FE: 5` #73
* \[x] Een footer met daarin de gegevens van Rotterdam en Conduction (gemaakt door Conduction in opdracht van) `FE: 3`

**Comment by lencodes** [comment]
> 2\. Een sub menu met daarin "Home", "Software", etc., hiervoor hebben we (nog) niet de data om te filteren dus dat zijn de vijf lagen geworden.

Dit moet wel de navigatie worden, missende data mag uit de Gateway beschikbaar gesteld gaan worden.

**Comment by lencodes** [comment]
Rotterdam en Conduction mogen linken naar rotterdam.nl en conduction.nl.

**Comment by rubenvdlinde** [comment]
Ik heb 

- model => Informatiemodel 
- process =>Proces 

toegevoegd aan de mogenlijke waarde voor `softwareType` in de [redoc](https://conduction.stoplight.io/docs/publiccode/00df95dbd9a93-create-component) definitie.  Dat betekend wel dat de API Repro OAS nog moet worden bijgewerkt voordat deze ook bruikbaar zijn.

**Comment by rubenvdlinde** [comment]
Ruben van der Linde commented: !image-20220721-092134.png|width=1220,height=1058!

* Bij het rechts boven menu zou ik voor commonground, haven en nldesign een link icoontje willen toevoegen en dan het menu item niet onderstreept
* Ik zou rechts boven graag een menu item documentatie toevoegen (met een documentatie ocoontje ervoor)
* Dat betekend dus ook dat ik graag een documentatie pagina zou willen hebben 😉 de mag nu nog even leeg zijn ← Uitwerken in los issue
* Ik zou onder de zoekbalk graag grijze vlaken toevoegen met daarin een herhaling van de menu items in het hoofdmenu (ex home) en een counter voor het aantal componenten van dat type (zodat je een beetje kan inschatten hoe groot open catalogi is)
* Ik zou graag (alle developer.overheid,nl) twee blokken willen hebben voor content (zie plaatje onder voor design)
** Over Open Catalogi
** Aan de slag met Open Catalogi
* Ik zou graag net als Developer.oerheid een wensen of feedback knop toevoegen (zie design onder aan de pagina) die doorlinkt naar [https://github.com/OpenCatalogi/.github/issues/new/choose|https://github.com/OpenCatalogi/.github/issues/new/choose] 
* De Footer is wat leeg die kunnen we echt wel een stuk verder vullen met wat lijstjes
** Links → Commonground, Haven, NL Design, Forum Standaardisatie
** Documentatie → Home, Over open catalogi, aan de slag met open catalogi, github
** Componenten → Shema’s, apis etc (herhaling van hoofd menu ex home)




!image-20220721-092700.png|width=1037,height=550!

!image-20220721-092808.png|width=1120,height=318!

**Comment by lencodes** [comment]
Feedback van @rubenvdlinde mogen w.m.b. in losse issues verder.

**Comment by rubenvdlinde** [comment]
Als het nieuwe issues worden dan mag (na het maken van de nieuwe issues) dit issue wel naar Done

**Comment by lencodes** [comment]
Feedback overgnomen in #143, #144, #145, #146, #147, #148.

**Comment by bbrands02** [comment]
Inladen van componenten en de mapping van softwareType zijn andere taken voor: #41 #141

**Comment by RonaldvCortenberghe** [comment]
is aanwezig

**Comment by RonaldvCortenberghe** [comment]
is aanwezig
