### ISSUE TITLE
Als beheerder wil ik GitHub Repositories kunnen synchroniseren

### ISSUE THREAD

**Issue by rjzondervan** [OpenCatalogi/.github#192]
Hier moeten we rekening houden met een aantal factoren, waarbij voornamelijk de rate limits van de GitHub APIs een rol spelen. Deze API heeft namelijk te maken met een secundaire rate limit die al vrij snel oplevert dat er geen nieuwe calls gedaan kunnen worden.

Het plan is daarom als volgt:
- [ ] We maken een plugin die de GitHub API bevraagt op een voorgeconfigureerd endpoint
  - Deze plugin moet afhankelijk zijn van de synchronisatie, en dus pas na de synchronisatie-acties worden afgetrapt
- [ ] Deze plugin roepen we aan via een cronjob
- [ ] We configureren meerdere cronjobs en plugins voor de hoeveelheid pagina's die github teruggeeft
- [ ] We bevragen vervolgens de publiccode.yaml die aan de repository vastzit en synchroniseren deze met de interne data

**Comment by RvdKlip** [comment]
Waarom wil 'een beheerder' dit? Wat levert dit functioneel op voor de gemeentelijke medewerker?

**Comment by rubenvdlinde** [comment]
Het verlaagd de drempel voor het aanbieden van software aan de catalogus en vergroot daarmee zowel de kwaliteit als kwantiteit van het aanbod. Hetgeen de medewerker een waardevollere catalogus opleverd.
