### ISSUE TITLE
Als dienstverlener wil ik aangeven dat ik gebruik maak van een componenten die reeds in de OpenCatalogi staat, zodat dit ook voor anderen inzichtelijk is

### ISSUE THREAD

**Issue by vwmvanbeek** [OpenCatalogi/.github#196]
### Project Location

Somewhere else (please specify in the description!)

### Describe the solution you'd like

Als ik een component opzoek (bijv. OpenFormulieren, Klantportaal/MijnGemeente of anders) dan kan ik bij dat component zien welke dienstverleners gebruik maken van dit component.

### Describe alternatives you've considered

none

### Additional context

Door te kijken wie gebruik maken van een component kan ik een inschatting maken van de robuustheid van een component

**Comment by RonaldvCortenberghe** [comment]
vwmvanbeek via mail benaderd. even afwachten
