### ISSUE TITLE
Als Dienstverlener(overheid) of leverancier wil ik componenten kunnen opvoeren in het federatieve deel, zodat dit inzichtelijk wordt voor andere dienstverleners en leveranciers

### ISSUE THREAD

**Issue by vwmvanbeek** [OpenCatalogi/.github#197]
### Project Location

Somewhere else (please specify in the description!)

### Describe the solution you'd like

Ik zou graag als dienstverlener of leverancier componenten kunnen opvoeren. Bij het opvoeren van een component denk ik ook aan het opvoeren van:

- algemene omschrijving
- Github locatie van de code
- leveranciers die de component ondersteunen, dienstverlening aanbieden (met link naar leverancierspagina)
- Dienstverleners (profit en non-profit) die het component afnemen (met link naar dienstverlener pagina)
- pagina aanmaken voor processen/modellen binnen het component (denk aan processen/implementaties binnen bijv GZAC/Valtimo of formulier definities binnen OpenFormulieren, dit kan ook een verwijzig zijn naar een Github pagina)

### Describe alternatives you've considered

none

**Comment by MWest2020** [comment]
Dit is inmiddels opgepakt.

**Comment by RonaldvCortenberghe** [comment]
OpenCatalogi leest github (en later Gitlab) uit dus beschrijven in repository via een publiccode.yml levert de gewenste functionaliteit op
