### ISSUE TITLE
Als concreet voorbeeld binnen OpenCatalogi zou ik graag OpenFormulieren willen opvoeren, zodat we direct een levendig voorbeeld hebben van de kracht van OpenCatalogi en zo de bijdrage en kennis van OpenCatalogi een boost krijgt vanuit de afnemers van OpenFormulieren

### ISSUE THREAD

**Issue by vwmvanbeek** [OpenCatalogi/.github#199]
### Project Location

Somewhere else (please specify in the description!)

### Describe the solution you'd like

In demo 2 werd gewerkt met  testdata en ik dacht dat de kracht van OpenCatalogi heel visueel wordt als je een daadwerkelijk component opvoert dat nu door ongeveer 15 gemeenten actief wordt gebruikt. Dat geeft meteen een boost een de OpenFormulieren community als ook de nog te vormen OpenCatalogi community. Interessant hierbij is dat er ook formulier definities kunnen worden gedeeld. HIervoor heeft  Maykin Media reeds een Github ingericht. Wellicht dat dit met de Public code YAML ook een synchronisatie kan krijgen naar opencatalogi.nl. De brongegevens staan op de Github, maar wellicht kan deze ook ingezien worden via de meer toegankelijke site van opencatalogi

### Describe alternatives you've considered

Potentiele alternatieven zijn Klantportaa/MijnGemeente en GZAC/Valtimo

**Comment by RonaldvCortenberghe** [comment]
vwmvanbeek via mail benaderd. even afwachten
