### ISSUE TITLE
Als gebruiker wil ik Lifecyclemanagement kunnen toepassen op componenten

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#2]
Uitvraag *De lifecycle van objecten kan worden bijgehouden in OpenCatalogi*

Dit onderwerp moet nader worden verdiept in is uitgewerkt in #36 

Issue is nu ingeschat conform de kleine definitie, ieder component heeft een status (string) die gelijk staat aan een keuze uit
- Gewenst
- Geplaned
- Beta
- Bruikbaar
- Uitgefaseerd

Acceptatie criteria:

- [x] Op het component detail scherm wordt de status (zoals hier boven) van het component getoont.

**Geblokkeerd door:**
- [x] #141

**Comment by rubenvdlinde** [comment]
sym.ver. is wel een ding. 

Let op, dit kent twee componenten
- Installaties die lopen
- Componenten an zich (dus ook end of live)

Zowiezo is er onderscheid tussen 
- Nog niet ge-onboord

**Comment by RonaldvCortenberghe** [comment]
we de status op detail pagina getoond hebben.  Dit gaat niet over lokale installaties. De lokale installaties worden verder afgehandeld is #49

**Comment by lencodes** [comment]
> Symentic Versioning toepasen -> https://semver.org/
> 
> Let op, dit kent twee componenten
> 
> * Installaties die lopen
> * Componenten an zich (dus ook end of live)
> 
> Zowiezo is er onderscheid tussen
> 
> * Nog niet ge-onboord
> 
> Betekend ook dat we losse installaties bijhouden ipv "component geinstalleerd"

Dit hoort (voor zover wij zien) onder sprint 3 in het issue #49.

**Comment by lencodes** [comment]
@RonaldvCortenberghe de waarden "Gewenst", "Gepland", etc. zijn momenteel niet beschikbaar in het API schema. Wel is hier een property `developmentStatus` met de waarden: `concept | development | beta | stable | obsolete`.

Worden deze bedoeld en zijn ze onjuist gedocumenteerd in dit issue of is het de wens dat er een _nieuw_ veld wordt aangemaakt hiervoor?

**Comment by rubenvdlinde** [comment]
@lencodes dit zijn dezelfde waarde, maar deze moeten dus (op de voorkant?) worden vertaald.

**Comment by lencodes** [comment]
Besproken tijdens de sprint planning: dit ticket gaat enkel over het tonen van de `developmentStatus` vertaald naar de labels zoals hierboven vernoemd. 

Zie bijbehorende task: #141.

**Comment by MWest2020** [comment]
closed after seeing done
