### ISSUE TITLE
Als gebruiker wil ik de onderlinge verbanden/afhankelijkheden zien tussen componenten

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#20]
Zo dat ik weet welke afhankelijkheden ik heb voor een bepaald product. 

Denk hierbij aan een applicatie die het ORC gebruikt om bepaalde objecten in op te slaan die heeft zowel het ORC nodig als bepaalde informatiemodellen.

**Afhankelijk van:**
- [x] #17 

**Taken**
- [ ] Sectie "maakt gebruik van" en "word gebruikt door" toevoegen
- [ ] Onderlinge verwijzingen opnemen in de metadata

**Acceptatiecriteria**
- Op de component detailpagina heb ik een sectie "Maakt gebruik van" en "wordt gebruikt door"
- Deze bevatten cards die doorverwijzen naar de detailpagina's van de betreffende componenten
- Bij meer dan twee rijen aan cards word paginering toegepast
- De cards worden gevuld vanuit de OpenCatalogi API

**Comment by MWest2020** [comment]
Ik zie dit wel terug in de UI, maar klopt het dat dit niet goed doorkomt?
