### ISSUE TITLE
[task]: Als gebruiker wil ik een logo aan de linkerkant van het hoofd menu

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#204]
### What is the goal of your request? Why should we do this?

Zodat ik weet van welke organisatie ik de catalogus aan het bekijken ben

![image](https://user-images.githubusercontent.com/4021899/185741837-8e92f56b-4c0e-4d98-9377-5f76baae1765.png)

### The acceptance criteria of the feature
1. Er staat een logo
2. Klikken op het logo voert terug naar de ome page

### Project Location

Homepage

**Comment by RonaldvCortenberghe** [comment]
done
