### ISSUE TITLE
[task]: Als gebruiker wil ik een inlog knop in het hoofd menu

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#205]
### What is the goal of your request? Why should we do this?

Zodat ik naar het inlogscherm kan navigeren

![image](https://user-images.githubusercontent.com/4021899/185741822-68270f05-9781-41ab-a447-81d9ad4a42fa.png)

### The acceptance criteria of the feature

1. Er is een inlogknop
2. Drukken op deze inlog knop brengt je naar de inlogpagina

### Project Location

Homepage

### Additional context

Voor nu mag de inlogpagina nog bestaan uit een username wachtwoord combinatie zonder dat die daadwerkenlijk iets doet, het verder uitwerken van inloggen valt onder andere issues

**Comment by RonaldvCortenberghe** [comment]
done
