### ISSUE TITLE
[task]: Als gebruiker wil ik kunnen kliken op het categorie overizcht

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#206]
### What is the goal of your request? Why should we do this?

Zodat ik in één keer alle componenten van een bepaald type kan indezien

![image](https://user-images.githubusercontent.com/4021899/185741940-3add310d-7343-4f3e-ab21-0534611990ec.png)

### The acceptance criteria of the feature

1. Klikken op een categorie brengt je naar het search scherm met de categorie ingevuld

### Project Location

Homepage

### Additional context

Er moeten even worden gecontroleerd of alle categorien nu ook goed in de publicc code hangen

**Comment by RonaldvCortenberghe** [comment]
done
