### ISSUE TITLE
[task]: Als gebruiker wil ik geen open catalogi in getallen

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#207]
### What is the goal of your request? Why should we do this?

Zodat ik minder informatie op de voorpagina heb

![image](https://user-images.githubusercontent.com/4021899/185741998-bf9198c8-e3da-48da-a804-ac098976bc00.png)

### The acceptance criteria of the feature

1. Dit component verwijderen

### Project Location

Homepage

### Additional context

Uiteindenlijk kunnen deze cijvers wel weer worden toegevoegd aan het type overizcht (zie designs van lennard)

**Comment by RonaldvCortenberghe** [comment]
done
