### ISSUE TITLE
[task]: Als gebruiker wil ik een redesign van de header op de overzichts pagina

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#214]
### What is the goal of your request? Why should we do this?

Zodat deze duidenlijker en beter leesbaar is en minder ruimte in neemt

### The acceptance criteria of the feature

1. Het onderschrift onder componenten mag weg (voegt niks toes)
2. Het filteren op lagen mag bij de andere filters staan (we hebben nu op twee plekken filters)
3. Het primaire filter mag naar boven (wel uitlijnen op de tabel

### Project Location

Componenten overzicht (zoek pagina)

### Additional context

![image](https://user-images.githubusercontent.com/4021899/185742763-ca35bcfd-0031-4ed4-92c0-bd9a293623ec.png)

**Comment by RonaldvCortenberghe** [comment]
done
