### ISSUE TITLE
[task]: Als gebruiker wil ik wil ik dat de detail link goed uitlijnt

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#215]
### What is the goal of your request? Why should we do this?

Zodat deze niet verspringt

### The acceptance criteria of the feature

1. De knop mag niet meer verspringen

### Project Location

Componenten overzicht (zoek pagina)

### Additional context

![image](https://user-images.githubusercontent.com/4021899/185743030-c5b21d23-37d6-4c5b-ba6a-185367391e85.png)

**Comment by RonaldvCortenberghe** [comment]
done
