### ISSUE TITLE
[task]: Als gebruiker wil ik dat de hele rij in de componenten tabel klikbaar is

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#216]
### What is the goal of your request? Why should we do this?

Zodat ik niet perse op de knop hoef te drukken

### The acceptance criteria of the feature

1. Bij het klikken op de tabel wordt de rij geopend

### Project Location

Componenten overzicht (zoek pagina)

### Additional context

![image](https://user-images.githubusercontent.com/4021899/185743064-7b436a18-a6d6-46bc-8bd7-13c7411f92c7.png)

**Comment by RonaldvCortenberghe** [comment]
done
