### ISSUE TITLE
[task]: Als gebruiker wil ik dat in de tabbelen de zelfde vormging voor labels worden gebruikt als in de cards

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#217]
### What is the goal of your request? Why should we do this?

Zodat ik een duidenlijk doorlopende visuele lijn heb

### The acceptance criteria of the feature

1. In de tabel worden dezelfde elementen gebruikt als in de cards

### Project Location

Componenten overzicht (zoek pagina)

### Additional context

Tabel
![image](https://user-images.githubusercontent.com/4021899/185743923-ac5ac5bf-a6aa-475d-9164-b1b2fc4e3463.png)

Card
![image](https://user-images.githubusercontent.com/4021899/185743941-db3f86da-1782-45eb-b6b7-932465ae3256.png)

Attentie!
Het gaat hier om de vormgeving, niet om welke ellementen we tonen

**Comment by RonaldvCortenberghe** [comment]
done
