### ISSUE TITLE
[task]: Als gebruiker wil ik ik dat inde componentlijst de harde kleur wordt gebruikt voor lagen

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#218]
### What is the goal of your request? Why should we do this?

Zodat het duidenlijk is dat het hier over lagen gaat (nu gebruiken we de zachte kleur die eigenlijk voor categorie bedoeld is)

### The acceptance criteria of the feature

1. De harde (donderker) kleuren worden gebruikt ipv de zache (lichte)

### Project Location

Homepage

### Additional context

![image](https://user-images.githubusercontent.com/4021899/185744014-4485dcc6-0e4a-4537-a7b7-72ed5543a13e.png)

**Comment by RonaldvCortenberghe** [comment]
done
