### ISSUE TITLE
[task]: Als gebruiker wil ik dat in de categorie lijst dezelfde vormgeving voor categorien wordt gebruikt als in de cards

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#219]
### What is the goal of your request? Why should we do this?

Zodat er een duidenlijke visuele lijn is

### The acceptance criteria of the feature

1. We gebruiken in de categorie lijst dezelfde vormgeving voor categorien als op de cards

### Project Location

Homepage

### Additional context

Categorielijst
![image](https://user-images.githubusercontent.com/4021899/185744152-b9e092b7-ba65-46d1-8e48-5cfbbfd8b948.png)

Card
![image](https://user-images.githubusercontent.com/4021899/185744129-295c37c3-7735-4f83-9e33-93571f0009c8.png)

**Comment by RonaldvCortenberghe** [comment]
done
