### ISSUE TITLE
[task]: Als gebruiker wil ik dat we in de categorielijst dezelfde iconen voor de laag titel zetten als die we in de card gebruiken

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#220]
### What is the goal of your request? Why should we do this?

Zodat er een duidenlijk visuele lijn is

### The acceptance criteria of the feature

1. In de categorielijst staat vooriedere laag titel een icoon van die laag

### Project Location

Homepage

### Additional context

Categorie lijst
![image](https://user-images.githubusercontent.com/4021899/185744189-59933ae4-1643-4737-943b-d034b36dd6a6.png)

**Comment by RonaldvCortenberghe** [comment]
done
