### ISSUE TITLE
[task]: Als gebruiker wil ik een redesign van de filter balk

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#221]
### What is the goal of your request? Why should we do this?

Zodat ik meer overzicht heb in mijn filters

### The acceptance criteria of the feature

- [x] #306 
- [x] #305 
- [ ] Totale resultaten met huidige filters tonen;

### Project Location

Componenten overzicht (zoek pagina)

### Additional context

Huidige filterbalk
![image](https://user-images.githubusercontent.com/4021899/185744428-709778ad-f37e-44a2-b1de-6fab354989fa.png)

Voorbeeld van [data.overheid.nl](https://data.overheid.nl/zoek?search=bla)
![image](https://user-images.githubusercontent.com/4021899/185744482-3299c5eb-9e19-407d-879b-bccc94e24c4f.png)

Voorbeeld van [developer.overheid.nl]()
![image](https://user-images.githubusercontent.com/4021899/185744512-48ea9f46-5537-42a0-8fb7-2d7b00191051.png)

Voor filters met minder dan 10 opties vind ik zelf checkboxes goed werken, geeft goed in een keer aan wat je mogenlijkheden zijn.  Bij meer opties kunnen of de huidige autocomplete aanhouden (maar dan moet je dus als sort of weten wat je zoekt) of het "meer alten zien" overnemen. Wat we van data.overheid.nl kunnen overnemen (of eigenlijk doorontwikkelen ze doen het zelf net iets anders) is het niet meteen laten zien van alle checkboxes onder een filter maar een soort van uitvouw optie bieden. Ze doen dan zelf met een + maar gevoelsmatig zou dat een chevron moeten zijn >

**Comment by rubenvdlinde** [comment]
Liefst in mvp maar niet de allerhoogste prio

**Comment by RonaldvCortenberghe** [comment]
Oplossing van Data.overheid.nl is charmant (inklapbaar en aantal hits) maar je lijkt niet meerdere optie te kunnen kiezen.
De developer.overheid.nl vind ik optisch minder aantrekkelijk maar biedt wel de mogelijkheid om meerdere te selecteren. de keuze onderaan "+ Alle opties" zou ook "> meer opties" kunnen worden inderdaad

**Comment by MWest2020** [comment]
Intussen een heel ander filter panel
