### ISSUE TITLE
[task]: Als gebruiker wil ik goede witruimte tussen labels in cards

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#223]
### What is the goal of your request? Why should we do this?

Zodat deze altijd hetzelfde is

### The acceptance criteria of the feature

1. Dat lijkt die nu niet te zijn

### Project Location

Componenten overzicht (zoek pagina)

### Additional context

![image](https://user-images.githubusercontent.com/4021899/185745026-347e1a5b-634a-411b-93ba-5de473e67984.png)

**Comment by RonaldvCortenberghe** [comment]
done
