### ISSUE TITLE
[task]: Als gebruiker wil ik bij labels achter het github of gitlab icoon het woord repository hebben

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#224]
### What is the goal of your request? Why should we do this?

Zodat het duidenlijk is dat ik hier dus ergens code of bestanden van kan zien

### The acceptance criteria of the feature

1. Achter het github label staat het woord repoistory (in cards, tabelen, detailpagina's en laagenweergaven)

### Project Location

Componenten overzicht (zoek pagina)

### Additional context

![image](https://user-images.githubusercontent.com/4021899/185745098-a33788b1-199e-4299-9d99-59c6001a5907.png)

**Comment by RonaldvCortenberghe** [comment]
done
