### ISSUE TITLE
[task]: Als gebruiker wil ik dat de witruimte boven de titel hetzelfde is als de witruimte onder de titel

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#226]
### What is the goal of your request? Why should we do this?

Zodat ik geen zinloze witruimte in mijn pagina heb op de detail pagina

### The acceptance criteria of the feature

1. De witruimte boven de titel is hetzelfde als wat die nu onder de titel is

### Project Location

Somewhere else (please specify in the description!)

### Additional context

![image](https://user-images.githubusercontent.com/4021899/185745286-ec706269-c879-4bac-b25a-640d8d3fcc9c.png)

**Comment by RonaldvCortenberghe** [comment]
done
