### ISSUE TITLE
[task]: Als gebruiker wil ik op de detail pagina de organisatie card gebruiken ipv een grijs blok

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#229]
### What is the goal of your request? Why should we do this?

Zodat er meer herkening en visuele lijn is

### The acceptance criteria of the feature

1. Grijze blok is vervangen door organisatie card

### Project Location

Somewhere else (please specify in the description!)

### Additional context

![image](https://user-images.githubusercontent.com/4021899/185745632-fec8089e-f272-493a-889e-e01b56459480.png)

Deze wordt geblokeerd door #228

**Comment by remko48** [comment]
Wordt niet langer geblokkeerd door #228
