### ISSUE TITLE
[task]: Als gebruiker wil ik hergebruik uitlichten

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#231]
### What is the goal of your request? Why should we do this?

Zodat ik kan zien welke organisaties ik kan benaderen voor gebruikers ervaring

### The acceptance criteria of the feature

- [x] Eigen (sub) titel
- [ ] Daaronder organisatie cards

### Project Location

Somewhere else (please specify in the description!)

### Additional context

Geblokeerd door #228

**Comment by lencodes** [comment]
`component.usedBy` is altijd een lege array (`[]`). Hierdoor kunnen we (nog) niet de échte organisaties tonen die een component hergebruiken.
