### ISSUE TITLE
[task]: Als gebruiker wil ik onderdaan de componenten lijst (be it tabel, card of lagen) een oproep tot toevoegen

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#232]
### What is the goal of your request? Why should we do this?

Zodat ik gebruikers motiveer om hun componenten toe te voegen

### The acceptance criteria of the feature

1. Onderaan de lijstweergave een component toevoegen blok toevoegen
2. Design in lijn met wensen en feedback blok
3. doorlingen naar https://opencatalogi.nl/documentation/usage

### Project Location

Componenten overzicht (zoek pagina)

### Additional context

Positie
![image](https://user-images.githubusercontent.com/4021899/185745907-595aeeb5-4a67-4eb8-baec-9a4a256f6672.png)

Vooorbeeld (wensen en feedback)
![image](https://user-images.githubusercontent.com/4021899/185745943-cd61b4de-fc2b-4edb-bd75-1e9e43db62e4.png)

**Comment by RonaldvCortenberghe** [comment]
Feedbackknop alleen zichtbaar op Home-pagina
