### ISSUE TITLE
[feature]: Als gebruiker wil ik een tile weergave van bedrijfsprocessen

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#239]
### What is the goal of your request? Why should we do this?

Zodat ik vanuit mijn business vraagstuk (b.v. vergunningen) kan zien welke eindoplossingen (en dus niet componenten) er beschikbaar zijn

### The acceptance criteria of the feature

1. Er een tiel weergave voor bedrijfsfuncties
2. Deze linkt door naar een vooringevuld filter

### Project Location

Componenten overzicht (zoekpagina)

**Comment by RonaldvCortenberghe** [comment]
IK zoek naar userstories v anuit de betreffende gebruikerskant. tot nu toe is er niets concreets en dus geen financiering
