### ISSUE TITLE
[Bug]: Niet overal Bolder lettertype gebruikt

### ISSUE THREAD

**Issue by sanderdegoose** [OpenCatalogi/.github#242]
### Operating system

MacOS Monterey 12.4

### Project Location

Frontend

### Instalation Location

Remote

### Bug description

Het is van belang om overal het Bolder lettertype te voeren. Dit is speciaal ontwikkeld voor Gemeente Rotterdam en komt de leesbaarheid ten goede. Dit is ook belangrijk m.b.t. de WCAG richtlijnen. In knoppen en in normale tekst zie ik nu een ander lettertype dan bijvoorbeeld in titels. Voor die laatste wordt wel Bolder gebruikt.

![Screenshot 2022-08-24 at 10 45 43](https://user-images.githubusercontent.com/111966876/186442902-8fc32729-1af6-4f0e-a368-4bbcd1bc6741.png)

**Comment by rubenvdlinde** [comment]
@RonaldvCortenberghe dan moet het bolder lettertype wel worden aangelevrd

**Comment by sanderdegoose** [comment]
Zeker! Bij deze

[Bolder.zip](https://github.com/OpenCatalogi/.github/files/9697086/Bolder.zip)
