### ISSUE TITLE
[Bug]: Externe links op een andere plek

### ISSUE THREAD

**Issue by sanderdegoose** [OpenCatalogi/.github#243]
### Operating system

macOS Monterey 12.4

### Project Location

Frontend

### Instalation Location

Remote

### Bug description

Nu wordt bovenaan de pagina een aantal externe links getoond. Normaal gesproken staan op deze plek de belangrijkste navigatie links (zoals home, software, processen, etc.) of ten minste de secundaire links (contact, kaart, inloggen, etc.). Bij binnenkomst op de pagina ging mijn ook meteen naar deze navigatie en begreep ik niet wat ik op deze pagina kon vinden. Pas toen ik ging zoeken viel mijn oog op de belangrijkste navigatie in het groene vlak. Het is beter om deze externe links in de footer te verwerken.

Zie het onderdeel 'header navigation' in ons Design System: https://www.figma.com/file/ZWSC4gCrOXRUR9UX3aoZ8x/Gemeente-Rotterdam-Design-System?node-id=1730%3A7404

De beste variant van de beschikbare headers in het design system voor dit project is overigens de tweede variant: 'Applications'.

![Screenshot 2022-08-24 at 10 45 43 copy](https://user-images.githubusercontent.com/111966876/186443904-6cf5dd9d-88b4-4b19-a5a7-af4b0583f11b.png)

**Comment by rubenvdlinde** [comment]
@remko48 eens, we zetten deze links in de footer, en plaatsen hier het hoofd menu. Daarmee vervalt het groene menu voor de niet admin pagina's
