### ISSUE TITLE
[Bug]: Header voldoet niet aan huisstijl

### ISSUE THREAD

**Issue by sanderdegoose** [OpenCatalogi/.github#244]
### Operating system

MacOS Monterey 12.4

### Project Location

Frontend

### Instalation Location

Remote

### Bug description

De header zoals deze nu bij OpenCatalogi wordt getoond, voldoet niet aan de huisstijl. Zo is er geen Gemeente Rotterdam logo aanwezig, staat de hoofdnavigatie op de verkeerde plaats en wordt er een groot groen vlak gebruik.

Bekijk het onderdeel 'Header navigatie' in het Design System (variant Applications) om een goed beeld te krijgen hoe het er uit zou moeten zien: https://www.figma.com/file/ZWSC4gCrOXRUR9UX3aoZ8x/Gemeente-Rotterdam-Design-System?node-id=1730%3A7404

![Screenshot 2022-08-24 at 16 28 06](https://user-images.githubusercontent.com/111966876/186445461-f94d168e-bf98-41a5-ad47-fb4b606cf337.png)

Verder is het belangrijk de titel en introductietekst (een introductietekst is niet noodzakelijk) onder de header te zetten. Zie hieronder een voorbeeld van Mijn Loket waarbij het groene vlak is gebruikt voor de zoekbalk en daaronder de titel en introductietekst komt.
![MIJN LOKET Desktop - Dashboard + parkeerproducten open](https://user-images.githubusercontent.com/111966876/186446653-b1e6183e-35cc-48d1-a7b6-590fdb423e73.png)

**Comment by rubenvdlinde** [comment]
@remko48 we pakken alleen het groene streepje onder het actieve menu item op
