### ISSUE TITLE
[Bug]: Navigatie pad onduidelijk met huidige header

### ISSUE THREAD

**Issue by sanderdegoose** [OpenCatalogi/.github#245]
### Operating system

macOS Monterey 12.4

### Project Location

Frontend

### Instalation Location

Remote

### Bug description

In de huidige opzet van de header / navigatie is het onduidelijk waar je je precies in de site navigatie bevindt. Dit komt doordat een duidelijke titel ontbreekt en ook het hoofdnavigatie item niet wordt ge-highlight. Dit is wel het geval in de header die we vanuit het Design System voorschrijven: https://www.figma.com/file/ZWSC4gCrOXRUR9UX3aoZ8x/Gemeente-Rotterdam-Design-System?node-id=1730%3A7404

Ik heb in het onderstaande voorbeeld het onderdeel 'Processen' geselecteerd in de hoofdnavigatie, maar nergens word ik herinnerd aan het feit dat ik op die pagina zit.

![Screenshot 2022-08-24 at 16 37 35](https://user-images.githubusercontent.com/111966876/186447915-9b052522-12c3-4ea9-bfa5-66fd358df451.png)

**Comment by rubenvdlinde** [comment]
Dit is een ui keuze gebaseerd op het verwijzen naar filters ipv pagina's
