### ISSUE TITLE
[Bug]: Tekst kleuren, groottes en regelafstanden

### ISSUE THREAD

**Issue by sanderdegoose** [OpenCatalogi/.github#247]
### Operating system

macoS Monterey 12.4

### Project Location

Frontend

### Instalation Location

Remote

### Bug description

![Screenshot 2022-08-24 at 16 28 06 copy](https://user-images.githubusercontent.com/111966876/186450465-946f03e1-c397-4b23-b8ba-73e129d4fafd.png)
![Screenshot 2022-08-24 at 10 46 39](https://user-images.githubusercontent.com/111966876/186450493-cc99ee5e-5c47-47e4-9102-9a9064833071.png)

Allereerst gebruiken we geen full black voor teksten, maar een donker grijze kleur (#404B4F - Tint 11 in het Design System). Zie hiervoor het onderdeel Colors uit het Design System: https://www.figma.com/file/ZWSC4gCrOXRUR9UX3aoZ8x/Gemeente-Rotterdam-Design-System?node-id=415%3A12199

Verder hanteren we d.m.v. een '8 pixel grid' voor iedere tekstgrootte een bepaalde regelafstand. Vanwege het 8 pixel grid zijn bijna alle voorgeschreven tekst groottes deelbaar door 8 (enkele uitzonderingen daar gelaten). Daarnaast is de regel dat de regelafstand 8 pixels groter is dan de tekstgrootte. Voorbeeld: bij een tekstgrootte van 48 pixels is de regelafstand 56 pixels. Of bij een tekstgrootte van 16 pixels de regelafstand 24 pixels.

Zie ook het onderdeel 'Headings' in het Design System: https://www.figma.com/file/ZWSC4gCrOXRUR9UX3aoZ8x/Gemeente-Rotterdam-Design-System?node-id=415%3A12207

**Comment by rubenvdlinde** [comment]
@remko48 tot in hoevere kunnen we dit nu verwerken in de design tokens? ik neem aan dat we in ieder geval de tekstkleur kunnen instellen?

**Comment by remko48** [comment]
De tekstkleuren zijn ingesteld via design tokens.
