### ISSUE TITLE
[Bug]: Footer voldoet niet aan huisstijl

### ISSUE THREAD

**Issue by sanderdegoose** [OpenCatalogi/.github#249]
### Operating system

Macos Monterey 12.4

### Project Location

Frontend

### Instalation Location

Remote

### Bug description

![Screenshot 2022-08-24 at 10 46 48](https://user-images.githubusercontent.com/111966876/186454703-c2ae7990-2e19-4bd1-903d-d7e2c53e6002.png)

De huidige footer voldoet niet aan de huisstijl. In ons Design System zijn twee typen footers opgenomen. De grote, groene 'default' footer wordt voornamelijk gebruikt op rotterdam.nl (in ontwikkeling), terwijl we voor applicatie die 'light' variant gebruiken. Mocht er behoefte zijn om meer kwijt te kunnen in een footer, dan kan de 'default' footer ook voor een applicatie worden gebruikt.

Zie de varianten in het Design System: https://www.figma.com/file/ZWSC4gCrOXRUR9UX3aoZ8x/Gemeente-Rotterdam-Design-System?node-id=590%3A28435

**Comment by rubenvdlinde** [comment]
Dit is de NL design footer, dus als er meer behoeften zijn aan footer opties meoten die worden ingebracht bij NL Design
