### ISSUE TITLE
[Bug]: 'Uitklap blok' met buttons voldoet niet aan huisstijl

### ISSUE THREAD

**Issue by sanderdegoose** [OpenCatalogi/.github#250]
### Operating system

MacOS Monterey 12.4

### Project Location

Frontend

### Instalation Location

Remote

### Bug description

![Screenshot 2022-08-24 at 10 46 20](https://user-images.githubusercontent.com/111966876/186599448-7880ecdb-3ced-4f88-b65e-6f10ef3b0d86.png)
![Screenshot 2022-08-25 at 09 11 55](https://user-images.githubusercontent.com/111966876/186599610-f88af44b-d274-4eef-ae9d-2c9df36489d5.png)
![Screenshot 2022-08-25 at 09 12 06](https://user-images.githubusercontent.com/111966876/186599627-de4e603c-40b9-45a2-ac6d-e709f1e73cc3.png)

Hoewel ik het qua UI / UX heel anders in zou richten, klopt de vormgeving de uitklap blokken met knoppen niet volgens de huisstijl. In het Design System voorzien we hierin d.m.v. een FAQ uitklap blok. Die zou je hiervoor ook kunnen gebruiken. Daarnaast is het qua UX gezien niet wenselijk dat de titels van de blokken 'uitgegrijsd' worden wanneer deze dichtgeklapt zijn. Dit impliceert dat iets niet (meer) beschikbaar is en deze manier van interactie gebruiken we dan ook het liefst zo min mogelijk.

Het FAQ uitklap is hier terug te vinden in het Design System: https://www.figma.com/file/ZWSC4gCrOXRUR9UX3aoZ8x/Gemeente-Rotterdam-Design-System?node-id=543%3A27142

**Comment by rubenvdlinde** [comment]
Dat is correct, het uitgrijzen gebeurd juist om aan te geven dat er geen beschickbaarheid is binnen een blok
