### ISSUE TITLE
[Bug]: Input fields / dropdown menu's voldoen niet aan huisstijl

### ISSUE THREAD

**Issue by sanderdegoose** [OpenCatalogi/.github#251]
### Operating system

macOS Monterey 12.4

### Project Location

Frontend

### Instalation Location

Remote

### Bug description

![Screenshot 2022-08-24 at 10 53 31](https://user-images.githubusercontent.com/111966876/186601165-1ad34923-293c-4845-861b-482f13741df4.png)

![Screenshot 2022-08-25 at 09 21 23](https://user-images.githubusercontent.com/111966876/186602571-80915077-41d7-4273-bf9a-9edbbcec0b9f.png)

De manier waarop input fields en dropdown menu's worden getoond, voldoet niet aan de huisstijl. Het is belangrijk dat deze elementen rechte hoeken hebben i.p.v. ronde hoeken. Ik zie nu ook twee verschillende stijlen door elkaar lopen, zowel rechte als ronde hoeken. In ons Design System hebben we over de styling van deze elementen veel over vastgelegd. Ook hoe dat bijvoorbeeld de interactie zou moeten zijn met een input field of dropdown. Bij bovenstaand screenshot zie ik bijvoorbeeld ook dat, wanneer ik een dropdown menu open klik, er een onderbroken lijn omheen komt te staan. Dit is niet de wenselijke manier van interactie. We gebruiken wel een dergelijke lijn om een input field of dropdown, maar dan niet onderbroken en alleen als de gebruiker met de tab-toets door de pagina navigeert (dit noemen we focus).
De 'selected' state, alsmede verschillende andere states zijn beschreven in het onderdeel Fields van het Design System: https://www.figma.com/file/ZWSC4gCrOXRUR9UX3aoZ8x/Gemeente-Rotterdam-Design-System?node-id=521%3A28176

**Comment by rubenvdlinde** [comment]
@remko48 zijn deze hoeken nu in te stellen via NL-Design?

**Comment by remko48** [comment]
Deze hoeken kwamen uit React en zijn nu rechthoekig.
