### ISSUE TITLE
[Bug]: Dropdown menu valt achter loader blok

### ISSUE THREAD

**Issue by sanderdegoose** [OpenCatalogi/.github#252]
### Operating system

macOS Monterey 12.4

### Project Location

Frontend

### Instalation Location

Remote

### Bug description

![Screenshot 2022-08-25 at 09 29 31](https://user-images.githubusercontent.com/111966876/186649556-a40ba32e-41c6-408c-a3c4-736053cebf25.png)

Als er een pagina of een onderdeel van de pagina wordt geladen en dat is zichtbaar d.m.v. een grijs 'ademend' blok, dan ligt dat over een dropdown menu heen, waardoor de content niet meer zichtbaar is.

**Comment by remko48** [comment]
Dit is opgelost door issue [#214](https://github.com/OpenCatalogi/.github/issues/214)
