### ISSUE TITLE
[feature]: Als gebruiker wil ik na het opstarten van OpenCatalogi graag éérst vanuit een 'bedrijfs-insteek' kijken naar de eindoplossingen (lees: alleen de laag 5 oplossingen) van mijn eigen organisatie, om daarna de mogelijkheid te krijgen mijn zoekgebied te verbreden naar één, meerdere, of alle andere gemeenten of het totale landelijke aanbod van eindoplossingen. Met daarna de mogelijkheid om in te zoomen op een eindoplossing.

### ISSUE THREAD

**Issue by RvdKlip** [OpenCatalogi/.github#253]
### What is the goal of your request? Why should we do this?

...zodat OpenCatalogi voor een doorsnee medewerker, direct inzicht geeft op de eigen organisatie (en niet een overload aan informatie krijgt. Zodat een doorsnee medewerker gemakkelijk op businessthema naar oplossingen kan zoeken.

### The acceptance criteria of the feature

1. gebruiksvriendelijk en intuïtief
2. overzichtelijk
3. doorzoekbaar op thema 

### Project Location

Componenten overzicht (zoek pagina)

### Additional context

![image](https://user-images.githubusercontent.com/38490649/187194839-c9352640-d743-4509-8ce8-cbe044854264.png)

**Comment by rubenvdlinde** [comment]
Voor thema's gebruiken we bedrijfsfuncties (zoeken we er een paar van uit).

**Comment by RvdKlip** [comment]
> 

De gemma bedrijfsfuncties zijn hiervoor goed om te gebruiken. Deze dus: https://www.gemmaonline.nl/index.php/GEMMA_Bedrijfsfuncties

Dus:
- Klant- en keteninteractie
- Uitvoering Sociaal Domein 
- Uitvoering Ruimtelijk Domein 
- Uitvoering Publieksdiensten
- Uitvoering Openbare orde en veiligheid
- Gegevensbeheer
- Uitvoering Sociaal Domein 
- Ondersteuning
