### ISSUE TITLE
[feature]: Als gebruiker wil ik direct de view hebben met 'Kaarten' op de startpagina en in de zoek/filterschermen

### ISSUE THREAD

**Issue by RvdKlip** [OpenCatalogi/.github#266]
### What is the goal of your request? Why should we do this?

Zodat ik de 'Portfoliopagina' te zien krijg
Zodat ik wat gebruiksvriendelijker naar het resultaat kan kijken.

### The acceptance criteria of the feature

als de instelling ook behouden blijven voor de volgende keer

### Project Location

Homepage

### Additional context

...en zoekpagina's.

**Comment by RonaldvCortenberghe** [comment]
volgens mij al gerealiseerd

**Comment by RvdKlip** [comment]
Yes
