### ISSUE TITLE
[Bug]: Ik wil metadata vastleggen bij mijn component. Moet dat in de publiccode ? en waar dan?

### ISSUE THREAD

**Issue by RvdKlip** [OpenCatalogi/.github#268]
### Operating system

Win 11 - Firefox webbrowser

### Project Location

Backend

### Instalation Location

Somewhere else (please specify in the description!)

### Bug description

Waar laat ik info over bijvoorbeeld de betreffende 'Bedrijfsfunctie'?  IN de YAML? Graag een template
Waar laat ik info over bijvoorbeeld de betreffende 'sub-Bedrijfsfunctie'?

**Comment by RvdKlip** [comment]
Na een tijdje zoeken en het terugkijken van een filmpje blijk dat een uitleg op een niet zo'n logische plek staat: https://github.com/OpenCatalogi/.github/blob/main/CONTRIBUTING.md

**Comment by RonaldvCortenberghe** [comment]
Ik zal dit even met Ruub doornemen

**Comment by RvdKlip** [comment]
nieuwe melding gemaakt met een concreet voorbeeld
