### ISSUE TITLE
[feature]: Als gebruiker wil ik een contact pagina

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#274]
### What is the goal of your request? Why should we do this?

Zodat ik kan zien wie ik moet benaderen voor vragen over open catalogi

### The acceptance criteria of the feature

1. Er is een pagina waarop contact gegevens staan
2 Hierop staan contact gegevens van Rotterdam
3. Hierop staan contact gegevens van conduction
4. Hier staan links voor de roadmap en het indienen van issues

### Project Location

Somewhere else (please specify in the description!)

**Comment by RonaldvCortenberghe** [comment]
al gerealiseerd , zo niet dan fase 2
