### ISSUE TITLE
[Bug:] Zoekveld op home pagina zoek alleen binnen componenten, dit veld zou minimaal ook op applicaties en categorieën moeten zoeken

### ISSUE THREAD

**Issue by RonaldvCortenberghe** [OpenCatalogi/.github#276]
### Operating system

Windows

### Project Location

Frontend

### Instalation Location

Remote

### Bug description

Het zoek veld op de home pagina zoekt alleen binnen de componenten. Eigenlijk zou dit op alles moeten zoeken binnen een catalogus.

**Comment by rubenvdlinde** [comment]
Let op, duplicaat issue
