### ISSUE TITLE
[feature]: Als gebruiker wil ik een aanpassing bij het zoeken

### ISSUE THREAD

**Issue by RonaldvCortenberghe** [OpenCatalogi/.github#280]
### What is the goal of your request? Why should we do this?

Zodat 

### The acceptance criteria of the feature

- [ ] Geen resultaat als je zoekt naar Rotterdam!?
- [ ] Hoe is het gesorteerd? Op rating? Ik wil weten waarop basis van gesorteerd is en ook zelf kunnen kiezen: Alfabetisch, op rating, op datum bijvoorbeeld

### Project Location

Homepage

**Comment by rubenvdlinde** [comment]
Dit gaat over component overstijgend zoeken
