### ISSUE TITLE
[feature]: Als gebruiker wil ik een aanpassing aan de componenten detailpagina

### ISSUE THREAD

**Issue by RonaldvCortenberghe** [OpenCatalogi/.github#281]
### What is the goal of your request? Why should we do this?

Zodat het verbeterd wordt

### The acceptance criteria of the feature

- [x] Tabbladen, bovenaan op de pagina willen we dit. En niet het woord tabblad erbij.
- [x] Verbanden  betere benaming is relaties
- [x] Technische gegevens  is niet zo technisch 😊 Andere benaming: ‘meer informatie’, of zelfs weg.
- [x] #284
- [ ] <s>Koppen zijn allemaal verschillende grootte lettertype</s>
- [ ] Linkjes zijn niet goed uitgelijnd

### Project Location

Component detail pagina

**Comment by remko48** [comment]
Het uitlijnen van de linkjes meten we nog reproduceren en zijn er nog niet achter waardoor dat komt.
