### ISSUE TITLE
[feature]: Als gebruiker wil ik een aanpassing bij de documentatie pagina's

### ISSUE THREAD

**Issue by RonaldvCortenberghe** [OpenCatalogi/.github#282]
### What is the goal of your request? Why should we do this?

Zodat het overzichtelijker wordt 

### The acceptance criteria of the feature

- [ ] Hooveren over bijv. Autonomie wordt lichtgroen waardoor het lijkt alsof het klikbaar is, maar dat is het niet
- [ ] Op dezelfde pagina: verschillende soorten lettertypes en groottes, graag consequent
- [ ] De links staan raar hoog in de regel
- [ ] Gekleurde tabel: lichte kleurtjes moeten sprankelender. Goed om de WCAG richtlijnen door te nemen. Verschillende lettertypes. 6 blokjes onderaan staan gek, door netjes onder elkaar te zetten kan de tabel smaller en dat leest prettiger. 

Bij Documentatie - Installatie:
- [ ] Bovenaan staat het pad in het Engels en zonder hoofdletters: documentation > installation. Dit is ook in het Engels en zonder hoofdletters op andere pagina’s -> consequent!

### Project Location

Documentatie pagina's

**Comment by remko48** [comment]
Hoveren over Autonomie hebben we niet kunnen reproduceren.
De Gekleurde tabel is een plaatje van de vng. We staan open voor een ander plaatje.
Het lokaliseren van de paden(url) staat op onze wensenlijst.
