### ISSUE TITLE
[feature]: Als gebruiker wil ik een tekstuele aanpassing

### ISSUE THREAD

**Issue by RonaldvCortenberghe** [OpenCatalogi/.github#289]
### What is the goal of your request? Why should we do this?

Zodat er niet Stratagie staat maar Strategie

![Uploading image.png…]()

### The acceptance criteria of the feature

Als er Strategie staat

### Project Location

Homepage

**Comment by rubenvdlinde** [comment]
Bij categorien op de homepagina en op de catgorien pagina

**Comment by MWest2020** [comment]
[veiligheid**s**ontwikkeling](https://opencatalogi.nl/categories/5b40c9bc-f1fb-4a43-a68f-437fa9eb7970)

[opdrachtverstrekking](https://opencatalogi.nl/categories/3ecd987f-c849-4803-9529-5a8fe20f45bb) (s kan weg)

[zorg dragen](https://opencatalogi.nl/categories) mist spatie. Meerdere instanties op pagina

[Financieel](https://opencatalogi.nl/categories/0d985db4-79a9-408e-8702-4f80a794815a) zonder trema

Onderaan in de footer: Common Ground. De g van ground moet een hoofdletter zijn
