### ISSUE TITLE
[Bug]: het lukt me niet om mijn component te publiceren in OpenCatalogi 

### ISSUE THREAD

**Issue by RvdKlip** [OpenCatalogi/.github#291]
### Operating system

win11

### Project Location

Backend

### Instalation Location

Somewhere else (please specify in the description!)

### Bug description

Ik heb een publiccode bestandje aan gemaakt voor mijn project en ik heb een webhook aangemaakt, maar mijn component wordt niet zichtbaar. 

Het gaat om https://github.com/Municipality-of-Rotterdam/Digitale-Balie en organisatie: https://github.com/Municipality-of-Rotterdam

**Comment by RonaldvCortenberghe** [comment]
IK zal dit nog even met Ruub na kijken

**Comment by RvdKlip** [comment]
Balie staat erin. Ik ga nog een andere proberen, dus als er wat loos is open ik een nieuw ticket
