### ISSUE TITLE
[feature]: Gateway-ui: als beheerder wil ik dat de cronjobs een status en IsEnabled hebben.

### ISSUE THREAD

**Issue by remko48** [OpenCatalogi/.github#299]
### What is the goal of your request? Why should we do this?

Zodat ik als beheerder kan zien wat de status van de cronjob is en als hij wel aan staat.

### The acceptance criteria of the feature

1. Er komt een status mee vanuit de backend.
2. De status en isEnabled worden juist weergegeven.

### Project Location

Beheerschermen

**Comment by MWest2020** [comment]
Deze functionaliteit is er.
