### ISSUE TITLE
Als gebruiker wil ik mijn componenten kunnen Publiceren

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#3]
Uitvraag: *Alle informatie uit de individuele OpenCatalogi kan worden gepubliceerd voor gebruik door andere deelnemers en het totaaloverzicht*

Opmerking 
Er zijn dus publieke en prive componenten

Gerelateerd aan
- #9 

Accepatie criteria
- [x] Als ik mijn component goed op github vermeld word deze voor de geselecteerde groepen en catalogi zichtbaar
- [x] Als ik mijn component in een eigen open catalogi opneem, word deze voor de geselecteerde groepen en catalogi zichtbaar
- [ ] Bovenstaande twee punten zijn goed en begrijpenlijk uitgelegd op opencatalogi.nl

**Comment by MWest2020** [comment]
Componentenuitleg wordt meegenomen met[ issue/335](https://github.com/OpenCatalogi/.github/issues/335)
