### ISSUE TITLE
[feature]: Als beheerder wil ik een object kunnen bewerken zonder JSON errors

### ISSUE THREAD

**Issue by remko48** [OpenCatalogi/.github#300]
### What is the goal of your request? Why should we do this?

Zodat ik het object kan bewerken.

### The acceptance criteria of the feature

1. Alle velden waar geen JSON wordt verwacht laat niet een `this is not valid JSON` error zien.

### Project Location

Beheerschermen

**Comment by lencodes** [comment]
De Gateway UI genereert deze formulieren a.d.h.v. een schema wat we terugkrijgen. Het veld `usedBy` is een `object`, waardoor die JSON verwacht. Dat dit formulier niet verzendt wanneer er een simpele string in geplaatst wordt, dat is de bedoeling.

Een mogelijke oplossing zou zijn:

- Het schema updaten naar `type=object, multiple=true, enum=[{organisatie},{organisatie},{organisatie},...]`;
- De Gateway UI updaten zodat wanneer bovenstaand schema geraakt wordt, we een `SelectMultiple` genereren met enkel de bovenstaande enum.

Hierna zou de gebruiker in de Gateway UI organisaties kunnen selecteren. 

Note: wij zijn dit eerder tegengekomen en er is al een draft gemaakt voor de benodigde changes in de Gateway UI (nog niet getest): https://github.com/ConductionNL/gateway-ui/pull/112/files.

**Comment by lencodes** [comment]
@remko48 heeft hier aan verder gewerkt (nog niet afgerond), staat op feature branch: `feature/OC-390/schema-object-fields`
