### ISSUE TITLE
[bug]: Als gebruiker wil ik dat de filters het doen.

### ISSUE THREAD

**Issue by remko48** [OpenCatalogi/.github#301]
### What is the goal of your request? Why should we do this?

zodat ik de componenten kan filteren.

### The acceptance criteria of the feature

1. De filter op laag werkt weer.
2. De rest van de filters werken ook weer.

### Project Location

Componenten overzicht (zoek pagina)

**Comment by lencodes** [comment]
In de frontend gaat het selecteren van een laag (specifiek: de laag "data") in combinatie met een multi select (e.g.: een categorie) fout.

Dit gaat fout i.v.m. een logica fout in het zetten van de nieuwe filter structuur (het selecteren kan inverted worden, e.g. wanneer je "data" aanzet, zet je 'm juist uit en andersom).

**Note:** dit issue was initieel aangemaakt omdat de backend filters het niet meer deden, we verwachten dat deze het ondertussen wel weer doen en testen dit door in dit issue, samen met de bovenstaande frontend issues.
