### ISSUE TITLE
[feature]: Als gebruiker wil ik dat ik geen dubbele data terug krijg

### ISSUE THREAD

**Issue by remko48** [OpenCatalogi/.github#303]
### What is the goal of your request? Why should we do this?

zodat ik geen pagina met alleenmaar de organisatie Utrecht zie.

### The acceptance criteria of the feature

1. Alle componenten/Applicaties/Organisaties/Catalogi/etc. worden maar 1 keer terug gegeven.

### Project Location

Homepage

**Comment by RonaldvCortenberghe** [comment]
fixed
