### ISSUE TITLE
[feature]: Als gebruiker wil ik dat er bij de catagorieën ook de juiste oplossingen staan.

### ISSUE THREAD

**Issue by remko48** [OpenCatalogi/.github#304]
### What is the goal of your request? Why should we do this?

zodat ik per categorie kan kijken wat de oplossingen zijn voor deze categorie

### The acceptance criteria of the feature

1. De juiste oplossingen staan bij de categorieën 

### Project Location

Homepage

**Comment by lencodes** [comment]
Hier moeten nog twee onderdelen ingeregeld worden:

(1) Data moet door de gateway aangeleverd worden (wélke componenten horen bij welke categorieën?) en
(2) Deze data moet door de frontend opgehaald en getoond worden.
