### ISSUE TITLE
[task] Categorieën filter updaten

### ISSUE THREAD

**Issue by lencodes** [OpenCatalogi/.github#308]
De huidige categorieën filter bevat nog de **oude** categorieën, deze moeten geüpdatet worden naar de **nieuwe** categorieën.

Note: de nieuwe categorieën zijn te vinden op `/categories`.

- [ ] De filters werken met de nieuwe categorieën en de oude zijn verwijderd.

**Comment by MWest2020** [comment]
Wordt overgenomen in nieuwe filtering
