### ISSUE TITLE
[feature]: Als gebruiker wil ik een overzicht hebben van de 'initiatieven' van gemeenten...

### ISSUE THREAD

**Issue by RvdKlip** [OpenCatalogi/.github#315]
### What is the goal of your request? Why should we do this?

...zodat ik weet welke gemeente met welk onderwerp bezig is of bezig gaat zijn **dit jaar**

### The acceptance criteria of the feature

Vanuit het menu Initiatieven...
1. het is mogelijk om een nieuw initiatief op te voeren als eindgebruiker
2. het is mogelijk om een overzicht te hebben van initiatieven waaraan gemeenten en VNG werken
3. de initiatieven hebben een globale omschrijving van doel en andere kenmerken
4. de initiatieven zijn als een 'roadmap' in een scherm te zien in tijd, maar ook in 5 lagen
5. vanuit de roadmap kan men downdrillen naar het initiatief   

### Project Location

Homepage

**Comment by RonaldvCortenberghe** [comment]
Is de roadmap van de issue's beperkt tot 1 jaar? En moet dat dynamisch zijn, dus vandaag plus 1 jaar of is en jaartal voldoende?

Voor wat betreft het opvoeren welke gegevens moeten er opgevoerd kunnen  worden?

Wordt er onder punt 2 benoemd overzicht hetzelfde bedoelt als onder punt 4 het roadmap in een scherm?
Wat zijn de andere kenmerken bij punt 3?
Moet er nog filtering mogelijk zijn zoja welke?

**Comment by RvdKlip** [comment]
Het is handig als de functionaliteit 'matched' met datgene wat men nodig heeft in het landelijke CG programma.
Ook Leeuwarden en Groningen hebben wensen op dit punt, maar welke?

**Comment by RvdKlip** [comment]
Bij punt 3. zijn dit de kenmerken (afkomstig uit portfolio spoor):
Initiatief, Dilemma, Categorie, Value statement, Laag, Scope, Herbruikbaar/opschaalbaar, Type eigenaar, Eigenaar, Onderdeel van programma (CG), Fase, Coalitievorm, Start, Eind, Eerste betekenisvolle stap(pen), Resources, Wat hebben we nodig? Productowner/contactpersoon, Strategische prioritering, Opmerkingen, Lokaal – landelijk, Naam CG component, Type Component, Status, Toelichting, Betekenis/Omschrijving in Jip en Janneke taal, Epic/Feature,
budget, tijd

**Comment by RvdKlip** [comment]
Bij punt 2, 4 en 5:
![image001](https://user-images.githubusercontent.com/38490649/225063483-c9b9668e-edb7-4fad-bd08-6e5565e32dbf.png)
![image006](https://user-images.githubusercontent.com/38490649/225063495-7ee3a616-b0b8-4108-8170-29f101ba9a73.png)
![image005](https://user-images.githubusercontent.com/38490649/225063501-a8b98ec6-dcb7-4907-96a8-e21946983406.png)
![image004](https://user-images.githubusercontent.com/38490649/225063505-10606472-abad-4f2e-aa72-bd905d35d6f6.png)

**Comment by RonaldvCortenberghe** [comment]
Ik ga dit even met Ruub bespreken

**Comment by RvdKlip** [comment]
Ik heb begrepen dat nadrukkelijk het verband met het landelijk portfoliio wordt gezocht, dus wat mij betreft kan deze dicht
