### ISSUE TITLE
[Bug]: Main landmark ontbreekt

### ISSUE THREAD

**Issue by savitris** [OpenCatalogi/.github#320]
### Operating system

macOS 13.3.1 (22E261)

### Project Location

Frontend

### Instalation Location

Remote

### Bug description

`https://opencatalogi.nl/`

 De `<html>` heeft geen `<main>` landmark

Huidige Landmarks:

- banner
- navigation
- navigation
- footer

**Comment by MWest2020** [comment]
Wordt meegenomen in de WCAG-epic
