### ISSUE TITLE
[Bug]: Form label ontbreekt

### ISSUE THREAD

**Issue by savitris** [OpenCatalogi/.github#325]
### Operating system

macOS 13.3.1 (22E261)

### Project Location

Frontend

### Instalation Location

Remote

### Bug description

`https://opencatalogi.nl/`

Het formuleer heeft geen label

`.HeaderTemplate-module--searchFormContainer--36619`
![Screenshot 2023-06-23 at 11 13 26](https://github.com/OpenCatalogi/.github/assets/11764984/42c8e406-577e-4b82-9e97-921108c77816)

**Comment by MWest2020** [comment]
Niet meer relevant
