### ISSUE TITLE
[Bug]: leeg button 

### ISSUE THREAD

**Issue by savitris** [OpenCatalogi/.github#326]
### Operating system

macOS 13.3.1 (22E261)

### Project Location

Frontend

### Instalation Location

Remote

### Bug description

`https://opencatalogi.nl`

De hamburger menu (op Mobile view) is leeg

De SVG is aria-hidden een heeft geen Accessible Name, dus VoiceOver leest _"button"_ 

De button is niet focusable

`<button class="PrimaryTopNav-module--menuToggle--d7cd5" style="cursor: pointer;">`

![Screenshot 2023-06-23 at 11 47 25](https://github.com/OpenCatalogi/.github/assets/11764984/62bc60c2-61e3-4037-b4be-06a965fab550)

**Comment by MWest2020** [comment]
Wordt meegenomen in WCAG-epic
