### ISSUE TITLE
[Bug]: peiltje icon in button niet uitgelijnd in mobile view

### ISSUE THREAD

**Issue by savitris** [OpenCatalogi/.github#327]
### Operating system

macOs 13.3.1 (22E261)

### Project Location

Frontend

### Instalation Location

Remote

### Bug description

`https://opencatalogi.nl/`

Het peiltje icon in de _"show more"_  buttons zijn niet uitgelijnd in mobile view

`utrecht-button utrecht-button--secondary-action CategoriesLandingDisplayTemplate-module--showMoreButton--c3550`

![Screenshot 2023-06-23 at 12 46 35](https://github.com/OpenCatalogi/.github/assets/11764984/ea3e6f07-a009-44d2-b43f-6f6e27ffd952)

**Comment by MWest2020** [comment]
Niet meer relevant. Knop in kwestie nederlands en uitgelijnd
