### ISSUE TITLE
[Bug]: geen Skip link in pagina

### ISSUE THREAD

**Issue by savitris** [OpenCatalogi/.github#329]
### Operating system

macOS 13.3.1 (22E261)

### Project Location

Frontend

### Instalation Location

Remote

### Bug description

`https://opencatalogi.nl/`

De pagina heeft geen Skip link om naar de Main Content te gaan
(Gerelateerde Issue [Main landmark ontbreekt #320](https://github.com/OpenCatalogi/.github/issues/320))

[NL Design System documentatie voor een Skip link](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css-component-skip-link--docs)

De onderstaande schermafbeelding toont de huidige navigatievolgorde
![Screenshot 2023-06-23 at 16 21 28](https://github.com/OpenCatalogi/.github/assets/11764984/995ad60f-da00-47e1-a944-61c6462244af)

**Comment by MWest2020** [comment]
Meegenomen in de WCAG-compliant maken epic. 

Naar verwachting 2024 Q2
