### ISSUE TITLE
[Bug]: niet alle pagina-inhoud is opgenomen in landmarks

### ISSUE THREAD

**Issue by savitris** [OpenCatalogi/.github#330]
### Operating system

macOS 13.3.1 (22E261)

### Project Location

Frontend

### Instalation Location

Remote

### Bug description

`https://opencatalogi.nl/`

Niet alle pagina-inhoud is opgenomen in landmarks

![Screenshot 2023-06-26 at 11 55 19](https://github.com/OpenCatalogi/.github/assets/11764984/fc590a24-d222-402f-a6ca-64e44ae697b3)

![opencatalogi nl Laptop (2023-06-26 09 47 42)](https://github.com/OpenCatalogi/.github/assets/11764984/af3d9f31-9b8d-46ab-8ede-ea76fd64024d)

**Comment by MWest2020** [comment]
Dit wordt opgepakt en naar verwachting ergens dit kwartaal in een grotere WCAG-complaint overhaul
