### ISSUE TITLE
[feature]: Als gemeente wil ik dat mijn organisatie en producten mooi op opencatalogi.nl staan, zodat het meerwaarde heeft om de openCatalogi en publiccode goed te vullen

### ISSUE THREAD

**Issue by EduardWitteveen** [OpenCatalogi/.github#331]

**Comment by EduardWitteveen** [comment]
Wij, gemeente SúdwestFryslân, staan op: https://opencatalogi.nl/ als organisatie, hier heb ik een aantal vragen over:

- Er is een https://github.com/Sudwest-Fryslan/.github/blob/main/openCatalogi.yaml aangemaakt, maar deze lijkt niet gebruikt te worden want:
	- Gemeente naam is anders dan in bestand
	- Genoemde software owned/used niet word overgenomen
	Het zou mooi zijn om hier advies bij te krijgen hoe hier een goede openCatalogi.yaml te maken, die netjes op de pagina toont.
	
- Er is een https://github.com/Sudwest-Fryslan/WebformulierenVerwerker/blob/main/publiccode.yaml aangemaakt, maar deze lijkt niet gebruikt te worden want:
	- Omschrijving ontbreekt
	- Andere velden ontbreken

Zodat onze organisatie en producten wat mooier smoelen op  https://opencatalogi.nl/

**Comment by MWest2020** [comment]
Deze wordt gesloten. Dit is inmiddels zeer mogelijk. Zie documentatie.opencatalogi.nl
