### ISSUE TITLE
[Bug]: Koppeling met ADFS levert een 500-melding op

### ISSUE THREAD

**Issue by RonaldvCortenberghe** [OpenCatalogi/.github#332]
### Operating system

Windows

### Project Location

Backend

### Instalation Location

Local

### Bug description

Inloggen via ADFS, levert een "500 internal Server Error" op.
Foutmelding gateway wijst op een lege array, ADFS levert een gevulde array. Mogelijk issue in "blackbox"Dex

**Comment by MWest2020** [comment]
@rjzondervan Wanneer er hier meer duidelijkheid over is/ een oplossing, wil je dan dit issues sluiten a.u.b.?

Updates ook welkom.

**Comment by MWest2020** [comment]
Opgelosd
