### ISSUE TITLE
[Bug]: Network errors bij openen log-pagina in de admin

### ISSUE THREAD

**Issue by RonaldvCortenberghe** [OpenCatalogi/.github#333]
### Operating system

Windows

### Project Location

Backend

### Instalation Location

Local

### Bug description

Na inloggen in de admin-kant gaan we naar de log-pagina. Ik kies een level "critical" en date/time en dan verschijnen er na enige tijd network error(s). 
Vermoedelijk overbelasting van de MongoDB

**Comment by MWest2020** [comment]
bugs vanaf nu af aan via support@conduction.nl
