### ISSUE TITLE
Ondersteuning MySQL

### ISSUE THREAD

**Issue by MWest2020** [OpenCatalogi/.github#336]
[Issue 28](https://github.com/OpenCatalogi/.github/issues/28) gesplitst tussen de documentatie, wat afgerond is en de ondersteuning voor MySQL.

**Comment by RonaldvCortenberghe** [comment]
Ooit hebben we afgesproken om ook MySQL te ondersteunen. In de gebruikte bronnen (code)  zat toen een bug in en hebben we dit laten liggen. Gaan we dit nu nog oppakken?

**Comment by MWest2020** [comment]
Bij het oppakken van deze functionaliteit voor nu ook de vraag:

Welke klant vraagt erom en met welk prio?

**Comment by MWest2020** [comment]
GEsloten en openen bij behoefte
