### ISSUE TITLE
[Bug]: Applicaties en Organisaties op Componenten pagina

### ISSUE THREAD

**Issue by RonaldvCortenberghe** [OpenCatalogi/.github#340]
### Operating system

Windows

### Project Location

Frontend

### Instalation Location

Local

### Bug description

Bij het navigeren naar de componentenpagina, verwacht ik daar alleen componenten te zien. Nu zie ik daar ook nog Applicaties en Organisaties, die allebei hun eigen pagina hebben

**Comment by MWest2020** [comment]
Gezien en voorgelegd in Slack

**Comment by MWest2020** [comment]
Deze wordt opgepakt als wijziging in de filtering
