### ISSUE TITLE
Als team wil ik een acceptatie omgeving

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#35]
Zodat ik user story's visueel kan reviewen

Voorstel is om hiervoor demomodam in te zetten

Acceptatie criteria:

- [ ] Acceptatie omgeving staat live op een server van de Gemeente Rotterdam.

**Comment by rubenvdlinde** [comment]
Deadline is 14 sept

**Comment by MWest2020** [comment]
er is een acceptatieomgeving inmiddels :)
