### ISSUE TITLE
[Bug]: Roadmap achterhaald?

### ISSUE THREAD

**Issue by MarcoKlerks** [OpenCatalogi/.github#366]
### Operating system

nvt

### Project Location

Somewhere else (please specify in the description!)

### Instalation Location

Somewhere else (please specify in the description!)

### Bug description

Zie https://github.com/OpenCatalogi/.github/blob/main/profile/README.md

Onder het kopje "Aanpak" staat een roadmap. Hierin wordt o.a. verwezen naar https://github.com/orgs/OpenCatalogi/projects/1 . Ik heb de indruk dat dit allemaal achterhaalde informatie is, toch?

**Comment by MarcoKlerks** [comment]
Overigens wordt later in de tekst ook nog een paar keer naar de _roadmap_ verwezen. Dat moet mogelijk ook nog aangepast worden.

**Comment by MarcoKlerks** [comment]
... en onder het kopje 'Bijdragen' staat dat mensen een "feature request" kunnen indienen. Als ik op de link klik kan ik echter alleen een bug of beveiligingsrisico melden.

**Comment by MWest2020** [comment]
Dank je voor het melden van deze punten @MarcoKlerks . De roadmap moet inderdaad bijgewertk worden. De templates zijn inmiddels wel geüpdate.
