### ISSUE TITLE
[Bug]: Foutieve links in Architectuur.md

### ISSUE THREAD

**Issue by MarcoKlerks** [OpenCatalogi/.github#367]
### Operating system

nvt

### Project Location

Somewhere else (please specify in the description!)

### Instalation Location

Somewhere else (please specify in the description!)

### Bug description

Zie https://github.com/OpenCatalogi/.github/blob/main/docs/handleidingen/Architectuur.md

- De link naar "OAS" (boven het tweede plaatje) klopt niet. Dat moet zijn: https://spec.openapis.org/oas/v3.1.0
- De link naar de "WHO" (onder kopje "Basisconfiguratie") klopt niet. Dat moet zijn: https://wetten.overheid.nl/BWBR0036795
- De link naar de Github van het publicatie Platform | Open Catalogi (onder kopje "Codebases")  klopt niet. Ik vermoed dat dat moet zijn: https://github.com/OpenCatalogi/web-app
- De link naar "OpenWoo.app" (onder kopje "Onder de motorkap") klopt niet. Dat moet zijn: https://openwoo.app/
- De link naar "fcs directory concept" (onder kopje "Meer over directory") klopt niet.
- De link naar "commonground.opencatalogi.nl" werkt niet goed. Even "https://" voor zetten.

**Comment by MWest2020** [comment]
Dank je voor het issue! Ik ga deze gelijk rechtzetten.

**Comment by MWest2020** [comment]
De punten zijn opgepakt en verwerkt.
