### ISSUE TITLE
Procedure pull request staat niet in contributing.md

### ISSUE THREAD

**Issue by MarcoKlerks** [OpenCatalogi/.github#368]
### Operating system

nvt

### Project Location

Somewhere else (please specify in the description!)

### Instalation Location

Somewhere else (please specify in the description!)

### Bug description

Zie: https://github.com/OpenCatalogi/.github/blob/main/docs/GOVERNANCE.md

Onder het kopje "bijdragen" wordt in het vierde punt verwezen naar contributing.md voor meer informatie over het bijdragen van code via een pull request. In de contributing.md staat echter informatie over hoe je je open source project op kunt nemen en vindbaar kunt maken via OpenCatalogi.

Zie: https://github.com/OpenCatalogi/.github/blob/main/docs/CONTRIBUTING.md

**Comment by MWest2020** [comment]
Bedankt voor het onder de aandacht brengen @MarcoKlerks.

Het CONTRIBUTING document heeft nu een note waarin we verwijzen naar de GitBook. 

![image](https://github.com/user-attachments/assets/f2882465-4967-4c2d-af09-ed938aa05fe1)
