### ISSUE TITLE
Informatie over beheerpartijen

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#42]
User Story  
* *Als:*  gebruiker
* *Wil ik:*  informatie over de beheerpartijen van een component kunnen zien
* *Zodat ik:*  contact op kan nemen met vragen en of opmerking over het component (Storingen)

**Beschrijving** 

Deze story beschrijft ....... 

zie ook #82 

**Acceptatiecriteria**: 

- [ ] Op de component detail pagina verwacht ik een overzicht met leveranciers
- [ ] Per leverancier verwacht ik contact informatie (naam, datum until, email, website, tel)

**Comment by RonaldvCortenberghe** [comment]
Ja partijen die een component in beheer hebben en dar de informatie van zoals helddesk, contact info etc.

**Comment by matthiasoliveiro** [comment]
Juist, dus moeten we laten zien wie (partij) welk beheer (technisch ,functioneel) aanbied

**Comment by rubenvdlinde** [comment]
Vanuit Publiccode wordt dit ondersteund als zijnde 

![image](https://user-images.githubusercontent.com/4021899/176588545-84a15499-e41d-4b2b-93cc-a25cc7ca3e6a.png)

Dat gaat echter over de partijen die de codebase beheren. In een open source gedachte zou ik verwachten dat leveranciers zelf zelf aangeven welke componenten zij ondersteunen (e.g. iemand kan managed open zaak aanbieden zonder dat open zaak daar iets over te zeggen heeft). Dat legt het verband andersom en betekend dat we per leverancier moeten bijhouden welke componenten deze ondersteund.

**Comment by RonaldvCortenberghe** [comment]
Het is van belang om verschillende aanvliegroutes te maken voor de verschillende soorten pagina's

**Comment by vwmvanbeek** [comment]
Bij OpenFormulieren zien we nog een andere rol. Daar wil Kodision zich ook presenteren als implementatiepartner. Dat wil bijv Maykin expliciet niet. Indien wij dus extra handen nodig hebben om de implementatie te versnellen dan bellen we niet Maykin (die doet wel beheer product, doorontwikkeling product), maar Kodision (configureren formulieren, regulier werk)

**Comment by JeroenGRotterdam** [comment]
Afhankelijk van beschikbaar zijn organisatie object in de gateway. Alleen tonen op detailpagina.
