### ISSUE TITLE
Notificeren en synchroniseren bronverwijzingen

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#45]
"User Story  
* *Als:*  gebruiker
* *Wil ik:*  notificaties ontvangen als er iets wijzigt op een component wat wij gebruiken (ook andere?)
* *Zodat ik:*  weet of die wijzigen invloed kunnen hebben op de werking van het component in mijn landschap

Beschrijving 

Bijvoorbeeld: scm is software configuratie management, of github

Deze story beschrijft ....... 

Notes:

- Notificaties mogen verlopen via het OpenCatalogi platform (en dus niet via mail of andere kanalen);
- Notificatie triggers zijn veranderingen in: `status` en `versie nummer`.

**Acceptatiecriteria:**

- [ ] Als gebruiker wil ik dat wijzigingen op aangewezen bronnen automatisch mee komen in mijn Catalogus
- [ ] Als gebruiker wil ik op de hoogte gesteld worden wanneer een component waar ik op geaboneerd ben of een component wat ik in gebruik heb wijzigt.

**Comment by rubenvdlinde** [comment]
SCM als in supply chain managment?

**Comment by RonaldvCortenberghe** [comment]
Is niet van mij maar ik vermoed Source Code Management. Zoals Github. dus als de status wijzigt dat je daat een notificatie van krijgt.
Ik vraag die uit bij de user

**Comment by RvdKlip** [comment]
Is mij niet bekend

**Comment by matthiasoliveiro** [comment]
Oplossingsrichting om te kunnen notificeren is om na inlog een pagina weer te geven met "gewijzigde" componenten

wel moeten we vaststellen wat een wijziging is voorstel voor nu: Status , Versie nummer

**Comment by RonaldvCortenberghe** [comment]
Voorstel akkoord

**Comment by JeroenGRotterdam** [comment]
Tweede acceptatie criteria afhankelijk van realisatie #29

**Comment by rubenvdlinde** [comment]
Een gewijzigd pagina voelt niet echt aan als notificeren, das redelijk passief (iemand moet eerst inloggen). Ik zou eerder een email verwachten.

**Comment by rjzondervan** [comment]
Ten dele geblokkeerd door #41

> Een gewijzigd pagina voelt niet echt aan als notificeren, das redelijk passief (iemand moet eerst inloggen). Ik zou eerder een email verwachten.
Deze functionaliteit wordt opgepakt in een andere story.

**Comment by rubenvdlinde** [comment]
- Volgen en ontvolgen via knopje op de component detail pagina
- Als je een component volgt komt deze op je  "mijn componenten pagina"
- Comopnenten die gewijzigd zijn sinds ze voor het laats zijn bekeken door de gebruiker worden op de pagina bovenaan getoond met een grafische waarschuwing.
