### ISSUE TITLE
Verplichting vanuit bewaartermijnen en archivering

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#46]
"User Story  
* *Als:*  Dataeigenaar
* *Wil ik:*  kunnen voldoen aan wet en regelgeving vwb gegevens gedurende de hele levenscyclus van een component.
* *Zodat ik:*  voldoe aan bewaartermijnen (en het ontsluiten van de data) en vernietigingstermijn. 

Beschrijving 

Op applicatiedata zitten in sommige gevallen wettelijk verplichte bewaartermijnen, geduende die termijnen  moet de data og wel geraadpleegd kunnen worden (WOB verzoeken) en na het termijn moet de data vernietigd worden (of op verzoek van de persoon zelf).
Ik weet niet of die hier echt van toepassing is, maar dat moeten we uitzoeken. Ook vernietiging van data na bewaartermijn tijdens de levensfase moet mogelijk zijn.
Deze story beschrijft ....... 

*Acceptatiecriteria:*

- [ ] Als gebruiker wil ik bij een component zien of het archivering conform zgw standaard ondersteund
- [ ] Als gebruiker wil ik bij een object type kunnen zien welke archivering van toepassing is

**Comment by rubenvdlinde** [comment]
Eigenlijk wil je hier de security officer als eindgebruiker

**Comment by RonaldvCortenberghe** [comment]
Wellicht is dit ook van belang voor onze recordsmanagers van Informatiebeheer.

**Comment by RonaldvCortenberghe** [comment]
onderbrengen in de ondersteunde standaardlijst
