### ISSUE TITLE
Als beheerder wil ik dat de applicaite voldoet aan alle door Rotterdam gestelde security eisen

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#47]
Zodat ik weet dat de applicatie veilig is

**Acceptatiecriteria:**

- [x] DPIA
- [ ] Pen test resultaat ([penttesttools.com](https://pentest-tools.com/))
- [ ] Snyck scan of vergelijkbaar (dependency injection)
- [ ] Fossa check (intellectueel eigendom)
- [ ] Container scan op veilige containers
- [ ] https://www.siteimprove.com/

**Comment by RonaldvCortenberghe** [comment]
De grote lijn is de security eisen en wensen van gemeenten in het algemeen. Specifieke Rotterdamse wensen kunnen nog toegevoegd worden

**Comment by RonaldvCortenberghe** [comment]
Matthias moet de maatregelen uit excel toepassen en aantonen
