### ISSUE TITLE
Releases en Productie kunnen onderhouden

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#50]
"User Story  
* *Als:*  
* *Wil ik:*  
* *Zodat ik:*  

Beschrijving 

Deze story beschrijft ....... 

**Acceptatiecriteria:**

- [ ] Als gebruiker wil ik versies kunnen opgeven en beheren bij componenten
- [ ] Als gebruiker wil ik versies kunnen opgeven en beheren bij installaties

**Comment by rubenvdlinde** [comment]
Voor dit user story heb ik meer details nodig voordat ik zou kunnen bepalen wie erbij zouden moeten komen zitten

**Comment by rubenvdlinde** [comment]
Voorstel is om deze te laten vervallen ten gunste #81

**Comment by RonaldvCortenberghe** [comment]
akkoord zie #49
