### ISSUE TITLE
Ideeën en nieuwe CG initiatieven

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#51]
"User Story  
* *Als:*  
* *Wil ik:*  
* *Zodat ik:*  

Beschrijving 

Deze story beschrijft ....... 

**Acceptatiecriteria:**

- [x] Als gebruiker wil ik componenten een status mee kunnen geven
- [ ] Als gebruiker wil ik een overzichts pagina van initiatieven

**Comment by rubenvdlinde** [comment]
Binnen de huidige componenten catalogus wordt dit afgevangen met de status "concept", de vraag hier is wel scope. Binnen open catalogi zijn we alleen de catalogus. Voor eventuele discussie, forums en product pagina's moeten we extern verwijzen (e.g. pleio)

**Comment by RonaldvCortenberghe** [comment]
Ik zou willen opteren voor een detailering van de statussen, zoals "in ontwikkeling", "concept", "mogelijke component", Afhankelijk van hoever in de tijd het gepland is. Verder zou daar een termijn aan toegevoegd moeten kunnen worden.

**Comment by RonaldvCortenberghe** [comment]
- Concept
- in Ontwikkeling
- Btea
- Bruikbaar
- uitgefaseerd
