### ISSUE TITLE
Ontsluiten : Downloaden

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#52]
"User Story  
* *Als:* gebruiker 
* *Wil ik:* een verwijzing naar (externe) bronnen (Github etc) waar vandaan down load kan plaatsvinden (of een download-knop_ 
* *Zodat ik:* niet zelf de bron hoef te benaderen (lees url in tikken) 

Beschrijving 

Deze story beschrijft ....... 

**Acceptatiecriteria:**

- [x] Als gebruiker wil ik op de component detail pagina een link naar de externe bron
- [ ] Als beheerder wil ik _meerdere_ links kunnen toevoegen
- [ ] Als beheerder wil ik bij de link kunnen opgeven wat voor link het is. 
- [ ] Als gebruiker wil ik per status/type component eisen stellen aan welke links verplicht zijn

**Comment by rubenvdlinde** [comment]
We moeten dan wel bepalen wanneer wat verplicht is en dat opschrijven in documentatie

**Comment by JeroenGRotterdam** [comment]
refinement en scoping op de gestelde acceptatiecriteria

**Comment by rjzondervan** [comment]
Zijn de acceptatiecriteria 2 t/m 4 hier relevant voor de downloadstory, of horen deze thuis in een aparte story? @RonaldvCortenberghe

**Comment by rubenvdlinde** [comment]
Is nu als volgt opgesteld ->

![image](https://user-images.githubusercontent.com/4021899/193566399-934ddd02-03e8-4d28-895f-298d7b6c69ab.png)
