### ISSUE TITLE
Technische afhankelijkheden

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#53]
"User Story  
* *Als* APM'er, beheerder en andere eindgebruiker,  
* *wil ik* aan de informatie van een component zien welke technische afhankelijkheden met infrastructurele voorzieningen er zijn voor het component 
* *zodat ik* in control blijf bij CRUD acties    

Beschrijving 

DIt om de impact van wijzigingen en inplementaties te kunen beoordelen, maar ook vooraf te kunnen zien welke technologie nodig is om een component in gebruik te nemen.   

**Acceptatiecriteria:**

- [x] Als gebruiker wil ik op de Component en Applicatie detail pagina een tabblad met technische afhankelijkheden
- [ ] Als gebruiker wil ik kunnen filteren op technische afhankelijkheden in het zoekscherm

**Comment by rubenvdlinde** [comment]
Dit word door PublicCode afgedekt binnen dependency managment

![image](https://user-images.githubusercontent.com/4021899/176594952-04ab0e9b-d651-487d-abd6-d8e10340839a.png)

**Comment by JeroenGRotterdam** [comment]
Dit wordt ook onder tab afhankelijkheden getoond
