### ISSUE TITLE
Relaties tussen lagen

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#55]
"User Story  
* *Als* APM'er en eindgebruiker,  
* *wil ik* aan de informatie van een component zien welke andere componenten worden gebruikt, en welke andere componenten gebruik maken, van het onderhavige component 
* *zodat ik* in lijn blijf met de landelijke standaard    

Beschrijving 

DIt om logische views/rapportages te kunnen maken en om impact (van bijvoorbeeld wijzigingen) te kunnen beoordelen. DIt om zodoende hergebruik en participatie te bevorderen, kosten te delen en efficienter met middelen om te gaan.   

Zie ook #54

**Comment by rubenvdlinde** [comment]
Volgens mij wordt de functionele wens van dit issue afgedekt door Zie ook #54
