### ISSUE TITLE
Visualisatie : Google search

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#57]
"User Story  
* *Als:* APM  
* *Wil ik:* Zoekresultaten hebben lijkende op ""google-search"" 
* *Zodat ik:* een overzicht van zoekresultaten heb en ze kan analyseren 

Beschrijving 

Deze story beschrijft ....... 

**Acceptatiecriteria:**

- [x] Als gebruiker wil ik een zoek scherm `FE: 5`
- [x] Op het zoekscherm wil ik een zoek balk voor het invoeren van zoekwoorden `FE: 5`
- [x] Ik wil de zoekresultaten kunnen weergeven als cards, tabel of lagen (aan de hand van resultaat icoontjes) `FE: 8`
- [x] Bij het zoeken wil ik kunnen filteren op: Type (Component, Applicatie, Schema, Proces, Organisatie, Status, Laag) (inschatting in onderliggende issues)
- [x] Na het zoeken wil ik zoek resultaten (dit is het resultaat van veel onderliggende issues en wordt daardoor niet in dit issue ingeschat, e.g.: #18, #78, #80, #77, #74, #76, #73, #71, #76)

**Comment by rubenvdlinde** [comment]
Bedoelen we hiermee blokjes met overichts informatie waarbij doorklikken leid tot een detail pagina?

**Comment by RonaldvCortenberghe** [comment]
Ja het lijkt mij wel makkelijk een overzichtspagina te krijgen met daarop de naam van het component en een korte beschrijving daarvan (die in de github aanwezig moet zijn). Zodat je snel kan scannen welke hits interessant zijn

**Comment by rubenvdlinde** [comment]
Dit is hoe zoeken er nu uitziet in de demo

![opencatalogi_component_overizcht](https://user-images.githubusercontent.com/4021899/176592387-a14a9ec3-1872-4f34-8efe-c787016f5861.png)

Dat kunnen we uitbreiden met extra zoekopties in lijn met developer.overheid

![develeoperoverheid_api_overizcht](https://user-images.githubusercontent.com/4021899/176592438-fda2043b-819a-4442-aea9-f671ffad4c68.png)

En een lagen weergaven alle huidige componenten catalogus

![componentencatalogus_overzicht](https://user-images.githubusercontent.com/4021899/176592517-3428d8bc-05a3-4d82-9b50-a7a6c6f3d7be.png)

**Comment by lencodes** [comment]
Voor zover ik zie is dit issue afgerond. Verdere doorontwikkeling hierop (a.d.h.v. feedback en refinement) kunnen nieuwe issues voor aangemaakt worden.

**Comment by RonaldvCortenberghe** [comment]
akkoord
