### ISSUE TITLE
Wetgeving

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#58]
"User Story  
* *Als* APM'er en eindgebruiker,  
* *wil ik* aan de informatie van een component zien welke wetgeving door het component is afgedekt en van toepassing is, 
* *zodat ik* in lijn blijf met de wet.    

 

Gegeven: (beschrijving van de uitgangssituatie) 
Als: (beschrijving van de actie) 
Dan: (beschrijving van de eindsituatie die nog acceptabel is) 

**Acceptatiecriteria:**

- [ ] Als gebruiker wil ik per component zien welke wet en regelgeving wordt afgedekt/gefaciliteerd
- [ ] Als gebruiker wil ik per applicatie zien welke wet en regelgeving  wordt afgedekt/gefaciliteerd

**Comment by rubenvdlinde** [comment]
Wat willen we doen met wetgeven? per component weergeven welke wetgeving van toepassing is?

**Comment by RonaldvCortenberghe** [comment]
Je wilt weten welke component we wanneer ten behoeve van welke wetgeving hebt gebruikt. Zodat je kan verantwoorden hoe men tot welke besluitvorming gekomen is. Stel er komt een wetswijziging, sinds wanneer hebben wij de juiste beslismodellen in place

**Comment by rubenvdlinde** [comment]
Waar we even op moeten letten is dat wat dek je af natuurlijk iets wezenlijks anders is dan wat is van toepassing op het component zelf. Dit moet in de UI dus extreem duidelijk zijn.

Mijn persoonlijke vraag is ook nog even hoe dit zich verhoudt tot UPL
