### ISSUE TITLE
Visualisatie obv GEMMA

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#59]
"User Story  
* *Als:* APM 
* *Wil ik:* overzichten kunnen maken op basis van GEMMA (bedrijfsfuncties, Bedrijfsservices, Applicatiefunctie, Referentie componenten) 
* *Zodat ik:* gerichte doorsnedes kan maken 

Beschrijving 

Deze story beschrijft ....... 

**Acceptatiecriteria:**

- [ ] Als gebruiker wil ik op de component en applicatie detail een card voor Gemma specificaties, met daarin bedrijfsfuncties, Bedrijfsservices, Applicatiefunctie, Referentie componenten

**Comment by rubenvdlinde** [comment]
Hoe zien we het verband met Gemma? Willen we bij een component aangeven welk Gemma component er met dit component wordt ingevuld?

**Comment by rubenvdlinde** [comment]
Toegevoegd aan dataschema

**Comment by lencodes** [comment]
@rubenvdlinde gaat het hier effectief over het tonen van gekoppelde `nl.gemma.*` ([zie PublicCode](https://conduction.stoplight.io/docs/publiccode/58v2ropv82qs8-component#:~:text=componnenten%20catalogue.-,gemma,array%5Bstring%5D,-apm)) objecten?



> Toegevoegd aan dataschema

Naar welke toevoeging refereer je hier?

**Comment by rubenvdlinde** [comment]
nl.gemma waar de bovenstaande dingen aan zijn toegevoegd

![image](https://user-images.githubusercontent.com/4021899/183407485-97d0c7d2-6189-471a-8a08-df8bfe39a52d.png)

**Comment by rubenvdlinde** [comment]
Uitgewerkt in #253

**Comment by rubenvdlinde** [comment]
Deze op done gezet omdat het nu teschnich rond is, weergave valt onde #253
