### ISSUE TITLE
Als  gebruiker wil ik datamanagement toepassen bij OpenCatalogi

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#6]
uitvraag *OpenCatalogi ondersteunt datamanagement*

Dit issue behoeft refinement, wat verstaan we onder datamanagement? De assumptie voor nu is dat hier het beheer van het gegevens landschap mee word bedoeld. Maar die moet worden gevalideerd bij de werkgroep

**Acceptatie Criteria**

- [x] -Als gebruiker wil ik bronnen kunnen toevoegen en verwijderen

**Comment by matthiasoliveiro** [comment]
Moet besproken worden met @RvdKlip en @JeroenGRotterdam

**Comment by RonaldvCortenberghe** [comment]
Dit slaat op datamanagement en data bronnen binnen de eigen gemeente

**Comment by RonaldvCortenberghe** [comment]
Contactpersoon die de bronnen beheert opsnorren

**Comment by rubenvdlinde** [comment]
Dit gaat over objecten op laag 1
