### ISSUE TITLE
Standaarden weergeven bij de componenten

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#60]
"User Story  
* *Als* APM'er en eindgebruiker,  
* *wil ik* aan de informatie van een component zien welke landelijke standaard door het component is afgedekt, 
* *zodat ik* in lijn blijf met de landelijke standaard    

Beschrijving 

Dit om hergebruik en participatie te bevorderen, kosten te delen en efficienter met middelen om te gaan   

**Acceptatiecriteria:**

- [ ] Als gebruiker wil ik in de component beschrijving zien welke standaarden worden ingevuld met dit component

**Comment by rubenvdlinde** [comment]
Wat is hier de onderliggende gedacht? Willen we per component weergeven welke standaarden (van bijvoorbeeld forum voor standaardisatie) zijn toegepast?

If so dan zouden we eigenlijk een lijst moeten aanbieden van standaarden de je zou moeten kunnen volgen

**Comment by matthiasoliveiro** [comment]
Zie voor het toevoegen van standaarden / referentie lijsten #101
