### ISSUE TITLE
Classificeren : UID

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#61]
"User Story  
* *Als:* APM 
* *Wil ik:* componenten een Unique Identifier mee kunnen geven (lokaal n gefedereerd) 
* *Zodat ik:*  

Beschrijving 

Deze story beschrijft ....... 

**Acceptatiecriteria:**

- [ ] Ieder component heeft een UUID
- [ ] Ieder gekloond en lokaal aangepast component heeft een source URI

**Comment by rubenvdlinde** [comment]
Bedoelen we hier met UID een universele identifier?

**Comment by matthiasoliveiro** [comment]
Toevoeging zo als maar niet uitsluitend als "Nick name" kunnen in latere stories worden opgepakt

**Comment by rubenvdlinde** [comment]
Dit is onderdeel van #25

**Comment by rubenvdlinde** [comment]
Technisch rond, dus op done
