### ISSUE TITLE
Classificeren ; Indexeren

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#63]
"User Story  
* *Als:* PO OpenCatalogi 
* *Wil ik:* een acceptabele perfomance hebben 
* *Zodat ik:*  een "acceptabele" response heb 

Beschrijving 

wil dit gaan werken dan moet de performance wel toereikend zijn, anders heeft dat een negatieve invloed op de acceptatiegraad en daarmee draagvlak.
Deze story beschrijft ....... 

**Acceptatiecriteria:**

- [ ] Als gebruiker wil ik dat een detail pagina onder 1 seconde (1000MS ) inlaad
- [ ] Als gebruiker wil ik dat een zoek overzicht pagina onder 1,5 seconde (1500ms) inlaad

**Comment by rubenvdlinde** [comment]
Hoe definiëren we deze, ik zou voorstellen een response tijd in seconde uiteen getrokken in target en minimaal. Deze kunnen we vervolgens opnemen in de definition of done. Bijvoorbeeld:

Iedere pagina zou binnen één seconde moeten inladen (renonce tijd onder de 1000) maar moet onder de 1,5 seconde inladen (1500MS) dit geld ook voor grotere bevragingen en zoekopdrachten.

**Comment by rubenvdlinde** [comment]
Wat mij betreft hoort deze eigenlijk thuis in de DOD #26

**Comment by RonaldvCortenberghe** [comment]
opgenomen in DoD
