### ISSUE TITLE
Attributen APM

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#64]
"User Story  
* *Als* APM'er (en andere gebruikers),  
* *wil ik* alle eigenschappen van componenten kunnen zien en bewerken (CRUD) conform de attributen die nodig zijn vanuit portfoliomanagement, 
* *zodat ik* het portfolio kan beheren   

Beschrijving 

Vanuit APM is het nodig informatie over componenten te hebben. Hiervoor is een begin-lijst aan attributen opgesteld. Deze is opvraagbaar bij RvC   

**Acceptatiecriteria:**

- [ ]

**Comment by rubenvdlinde** [comment]
Wie gaat deze lijst ophalen en bij voorkeur toevoegen aan dit issue?

**Comment by RonaldvCortenberghe** [comment]
@rubenvdlinde @matthiasoliveiro
[OneDrive_1_27-6-2022.zip](https://github.com/OpenCatalogi/.github/files/8990135/OneDrive_1_27-6-2022.zip)
?

**Comment by rubenvdlinde** [comment]
Actie @rubenvdlinde en @matthiasoliveiro deze attributen naast public code houden en uitlijnen

**Comment by matthiasoliveiro** [comment]
Dit issue wordt opgepakt in issue #62 hier worden de rollen in bepaald.
