### ISSUE TITLE
Publiceren aan wie?

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#66]
"User Story  
* *Als:* APM en architect
* *Wil ik:* kunnen bepalen aan wie welke gegevens van een component gepubliceerd mogen worden 
* *Zodat ik:* kan voorkomen dat niet openbare informatie gepubliceerd wordt 

Beschrijving 

Deze story beschrijft ....... 

**Acceptatiecriteria:**

- [ ] Als gebruiker kan ik doelgroepen (organisatie typen) opgeven waarmee ik een component deel
- [ ] Als gebruiker kan ik één of meerdere specifieke organisaties opgeven om een component mee te delen
- [ ] Dit wordt gecontroleerd aan de hand van PKI certificaat

**Comment by rubenvdlinde** [comment]
Hebben we een voorbeeld van niet openbare metadata? (WOB ook even in het achterhoofd houdende)

**Comment by rubenvdlinde** [comment]
Ik denk dat het te vergaat om dit per gegeven in de gegeven set te gaan configureren. Mijn gevoel is eerder dat we moeten kijken naar alle gegevens in de set en dan bepaalde gegevens aanwijzen (persoons gegevens) waar we ander mee omgaan.

Globaler vraag ik me echter af of we het verspreiden van persoons gegevens niet gewoon kunnen voorkomen door ze uit te sluiten van de gegevens set.

Met betrekking tot vertrouwelijke componenten ivm handhaving is er nu een idee om het specifiek delen van componenten met andere organisaties te ondersteunen via #69 . Voor gevoelige componenten zou ik dan simpekweg zeggen niet delen.
