### ISSUE TITLE
Publiceren per gegeven

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#67]
Geblokkeerd door #64 en #10

"User Story  
* *Als:* componenteigenaar en architect
* *Wil ik:* kunnen bepalen welke gegevens wel gepubliceerd worden (en wanneer) en welke niet
* *Zodat ik:* kan voldoen aan de AVG

Beschrijving 

In sommige gevallen is he wellicht niet wenselijk dat er persoonsgegevens gepubliceerd worden en in andere gevallen (bijvoorbeeld als contactgegevens van beheerders etc) wel. 

Deze story beschrijft ....... 

**Acceptatiecriteria:**

- [ ] ...

**Comment by rubenvdlinde** [comment]
Ik denk dat we hiervoor eerst de gegevens zet moeten bepalen, daarvoor is een ander issue

**Comment by rubenvdlinde** [comment]
Zie ook #66

**Comment by rubenvdlinde** [comment]
Is dit voor mensen die handelen uit hoofde van hun functie wel een probleem als het gaat om zakenlijke contactgegevens?

**Comment by rubenvdlinde** [comment]
We geven gebruikers de mogenlijkheid om zelf hun email addres en telefoon nummer in te vullen. Daarmee zijn ze ook zelf ion controlle over het al dan niet delen van deze gegevens.
