### ISSUE TITLE
Publiceren naar doelgroep

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#69]
"User Story  
* *Als:* component-eigenaar 
* *Wil ik:* kunnen bepalen of mijn component voor Lokaal, publiekelijk gebruik is of voor een selecte doelgroep 
* *Zodat ik:* aan kan geven wie het bestaan van het component kan zien 

Beschrijving 

Deze story beschrijft ....... 

 **Acceptatiecriteria:**

- [ ] Als gebruiker wil ik kunnen aangeven met welke organisaties ik  componenten en applicaties deel

**Comment by rubenvdlinde** [comment]
Zie #68 voor gedachten over doelgroepen

**Comment by rubenvdlinde** [comment]
Doelgroep is hier intern versus extern, m.a.w. publiceer ik het component ook naar de landelijke catalogus

Overigens ken public code van zichzelf  ook een intendedAudience. Dat is (zo al je van de EU zou verwachten) gefocused op landen. Maar kent ook scopes (branches) zie -> https://conduction.stoplight.io/docs/publiccode/58v2ropv82qs8-component en dan intendedAudience.

We zouden die simpelweg kunnen uitbreiden (via de NL property) met een extra property
- intendedOrganisations <- een array van organisaties waarmee het component wordt gedeeld (daar kan de landelijke catalogus er dan één van zijn)

Voorstel nu ook uitgewerkt in stoplight onder de nl extensie

**Comment by RonaldvCortenberghe** [comment]
zie #121
