### ISSUE TITLE
Zoeken per gemeente

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#71]
"User Story  
* *Als:* APM 
* *Wil ik:* kunnen zoeken naar bepaalde gemeente(n ) 
* *Zodat ik:* kan zoeken naar oplossingen binnen vergelijkbare gemeenten 

  

Beschrijving 

Deze story beschrijft ....... 

**Taken**
#130
#131

**Acceptatiecriteria:**

- [ ] Als gebruiker wil ik een filter organisaties op de zoek pagina naar organisaties die leveren en organisaties die gebruiken. `FE: 5`
- [ ] Als gebruiker wil ik een een organisatie detail pagina waarop ik kan zien welke componenten een organisatie in zijn catalogi heeft opgenomen `FE: 8`

**Comment by rubenvdlinde** [comment]
Even assumptie testen maar dan willen we denk ik kunnen zoeken op
- Organisaties die componenten gebruiken
- Organisaties die componenten leveren

Met andere woorden iets breder dan gemeenten, en op twee manieren kijken, wie gebruikt wat en wie levert wat.

**Comment by lencodes** [comment]
Dit issue is opgepakt voor de frontend filtering, filtering en communicatie met de backend pakken we nu dus (nog) niet op!

**Comment by vwmvanbeek** [comment]
Is het een idee om gemeente als contributor te zien. We zijn uit op multi-vendor, daarom is het eigenlijk belangrijk om te weten welke leveranciers het component ondersteunen, bij welke dienstverleners het component actief is en welke dienstverleners actief contributen.

**Comment by bbrands02** [comment]
Organisaties die componenten gebruiken kunnen we kwijt in usedBy en organisaties die eraan werken/leveren in maintenance.contractors.

**Comment by lencodes** [comment]
@bbrands02 @rjzondervan om deze filtering in de frontend werkend te krijgen hebben we een endpoint nodig waarin we alle organisaties kunnen ophalen.

(Deze array aan organisaties gebruiken we vervolgens om de select te vullen)

**Comment by rubenvdlinde** [comment]
Lennart Bank commented: Hiervoor is eerst een backend endpoint nodig met alle organisaties.

**Comment by lencodes** [comment]
Alles wat nog moet gebeuren voor dit issue is gedocumenteerd in #77, daarom sluit ik dit issue.

**Comment by rubenvdlinde** [comment]
Done
