### ISSUE TITLE
Zoeken op 5-laags informatiemodel

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#72]
"User Story  
* *Als:* APM 
* *Wil ik:* kunnen zoeken per laag van het 5-laags informatiemodel, maar ook over alle lagen heen 
* *Zodat ik:* (beschrijving van de reden waarom dat ontwikkeld moet worden) 

Beschrijving 

Deze story beschrijft ....... 

**Acceptatiecriteria:**

- [x] Als gebruiker wil ik op de zoek pagina kunnen filteren op de lagen van het commonground model `FE: 5`

**Comment by rubenvdlinde** [comment]
Voor mijn gevoel is dit dan onderdeel van het zoek filter

**Comment by RonaldvCortenberghe** [comment]
Dat gevoel herken ik, bespreken

**Comment by lencodes** [comment]
Dit issue is opgepakt voor de frontend filtering, filtering en communicatie met de backend pakken we nu dus (nog) niet op!

**Comment by bbrands02** [comment]
Filter werkt op nl.commonground.layerType

**Comment by rubenvdlinde** [comment]
Done
