### ISSUE TITLE
Zoeken op vrije tekst

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#73]
"User Story  
* *Als:* APM 
* *Wil ik:* kunnen zoeken op een free format tekstveld 
* *Zodat ik:* niet altijd precieze naamgeving hoeft te weten 

Beschrijving 

Deze story beschrijft ....... 

**Acceptatiecriteria:**

- [ ] Als gebruiker wil ik kunnen zoeken in een vrij zoekveld dat een partial match uitvoert op naam + description `FE: 5` `BE: ?`

**Comment by rubenvdlinde** [comment]
Eigenlijk is het enige wat we dan even moeten weten in welke velden er dan gezocht moet worden

**Comment by RonaldvCortenberghe** [comment]
Als we ook bepaalde velden als zoek veld gedefinieerd hebben, zal dit voornamelijk op omschrijvingsveld gaan lijkt me (wellicht ook de gedefinieerde velden meenemen?)

**Comment by rubenvdlinde** [comment]
Dus naam + omschrijving veld?

**Comment by rubenvdlinde** [comment]
Dit is hoe we dat nu hebben opgezet 

![opencatalogi_component_overizcht](https://user-images.githubusercontent.com/4021899/176599339-7d8813c7-5fd5-4748-b490-b6b7fcf24173.png)

**Comment by lencodes** [comment]
@rjzondervan kijkend naar dit issue komen wij tot de conclusie dat het zoeken op title en description op zichzelf makkelijk is. Echter zal er een keuze gemaakt moeten worden hoe zwaar we de titel vs de description laten wegen.

Wij schatten de frontend hier in en laten deze afweging dus volledig buiten beschouwing.

**Comment by bbrands02** [comment]
Dit wordt makkelijker als we het nieuwe queryParameter ojbect in de gateway gebouwd hebben waar partial search onder valt. Het is al mogelijk maar op een ongewenste manier.

**Comment by rubenvdlinde** [comment]
Maar het queryParameter object is nu nog niet toegevoegd toch? En voor mij is het ook nog even de vraag of we dat gaan doen. Dus door hem daar aan vast te hangen creëren we een harde impediment.

Ik zou toch willen voorstellen om het op de huidige manier te doen (die reeds werkt) ipv in te zetten op toekomstige ontwikkelingen.

**Comment by rubenvdlinde** [comment]
Done
