### ISSUE TITLE
Zoeken op Gemma indeling

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#74]
"User Story  
* *Als:* APM 
* *Wil ik:* kunnen zoeken op de GEMMA2-indeling i.c. Bedrijfsfuncties, Applicatiefuncties en Referentiecomponenten 
* *Zodat ik:* snel gericht een beeld kan krijgen welke oplossingen er zijn voor bepaalde functionaliteiten 

Beschrijving 

Deze story beschrijft ....... 

**Geblokkeerd door**
- [x] Objecten een endpoints voor GEMMA objecten  #128
- [ ] #142
- [ ] #140

**Acceptatiecriteria:**

- [ ] Als gebruiker wil ik op de zoek pagina kunnen filteren op de onder #59 genoemde kenmerken

**Comment by rubenvdlinde** [comment]
Deze moeten we wel scopen op een gelimiteerde zet aan gemma atributen, anders bouwen we Gemma na

**Comment by rubenvdlinde** [comment]
Hebben we een overzicht van Gemma attributen of de Gemma api, er zat bij de kickof iemand van de software catalogus toch?

**Comment by rubenvdlinde** [comment]
Gemma attributen worden nu gedefinieerd onder #59

**Comment by lencodes** [comment]
Dit issue is opgepakt voor de frontend filtering, filtering en communicatie met de backend pakken we nu dus (nog) niet op!

**Comment by vwmvanbeek** [comment]
Klip R. van der (Ruub) <r.vanderklip@Rotterdam.nl> heeft ons in G4 overleg een GEMMA overzicht laten zien met daarin een eerste plotting van de CG-componenten. Die was zeer verhelderend. En is een hele mooie ingang voor componenten die daadwerkelijk invulling geven aan GEMMA componenten. Denk hierbij aan formulieren, portaal, chatbot... Dit is een andere view dan wanneer je naar Diensten kijkt als huwelijk, MOR, Burgerzaken

**Comment by bbrands02** [comment]
Filteren kan op nl.gemma

**Comment by stephanieweerdenburg** [comment]
Ronald levert list of values aan

**Comment by RonaldvCortenberghe** [comment]
GEMMA2 bjecten

[GEMMA2 Objecten.xlsx](https://github.com/OpenCatalogi/.github/files/9092978/GEMMA2.Objecten.xlsx)

**Comment by RonaldvCortenberghe** [comment]
Issue aanmaken voor uitgebreid zoeken, voor nu gaan we er van uit dat de objecten in de publiccode zijn toegevoegd

**Comment by RonaldvCortenberghe** [comment]
zie #121

**Comment by lencodes** [comment]
@bbrands02 @rjzondervan ik heb de xlsx bestanden omgezet naar `json` bestanden, zie hieronder.

[gemma-objecten.zip](https://github.com/OpenCatalogi/.github/files/9111090/gemma-objecten.zip)

**Comment by lencodes** [comment]
@bbrands02 om deze filter werkzaam te maken moeten de huidige `gemma` endpoints geüpdatet worden zodat de data consistent wordt én moet de `array` filter bug gefixt worden.

**Comment by matthiasoliveiro** [comment]
Issues #142 & #149 zijn voorwaardelijk voor de uitvoer van dit issue

**Comment by rjzondervan** [comment]
Om #149 te omzeilen stellen we voor om hier elasticsearch tussen te zetten zolang de bug niet is verholpen.

**Comment by rubenvdlinde** [comment]
Done
