### ISSUE TITLE
Zoeken op gedefinieerde velden

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#75]
"User Story  
* *Als:* APM 
* *Wil ik:* kunnen zoeken op vooraf gedefinieerde velden (bijv. metadata-velden) 
* *Zodat ik:* sneller een gerichter zoekresultaat kan hebben 

Beschrijving 

Deze story beschrijft ....... 

**Taken**
- [ ] #142
- ~Sorteren op meer velden dan datetime (alfabetisch, numeriek)~ (Verplaats, zie: https://github.com/OpenCatalogi/.github/issues/180)

 **Acceptatiecriteria:**

- [ ] Als gebruiker wil ik kunnen zoeken op Platform, Software Type, License, Maintenance.type  `FE: 20` `BE: 1`

**Comment by rubenvdlinde** [comment]
Vraag is dan even welke velden :)

**Comment by RonaldvCortenberghe** [comment]
Uit de inventarisatie van welke gegevens per welke laag vastgelegd moeten worden, blijkt denk ik dat er een aantal gegeven (velden) Generiek zijn voor componenten en een aantal specifiek voor een laag. Het zal in eerste instantie gaan om de generieke gegevens maar ook daar moeten we nog even een selectie in maken

**Comment by rubenvdlinde** [comment]
wat we kunnen doen is het data model erbij pakken en kijken op welke waarde je zou willen filteren, dat is echter wel gevaarlijk in die zin dat we dan snel te veel en complexe filters gaan maken. 

https://conduction.stoplight.io/docs/publiccode/58v2ropv82qs8-component

**Comment by rubenvdlinde** [comment]
Alle opties binnen een filter zijn OF filters bij elkaar zijn EN

**Comment by lencodes** [comment]
Dit issue is opgepakt voor de frontend filtering, filtering en communicatie met de backend pakken we nu dus (nog) niet op!

**Comment by lencodes** [comment]
> [ ] Als gebruiker wil ik kunnen ordenen op termen waar ik ook op kan zoeken

Als eerste versie gaan we sortering inbouwen gebaseerd op: datum, naam, hoeveelheid installaties.

**Comment by bbrands02** [comment]
Voor orderen op de gateway moet er nog wat gebouwd worden. Momenteel kan er alleen geordered worden op dateCreated en dateModified.

**Comment by stephanieweerdenburg** [comment]
Splitsen: 'Als gebruiker wil ik kunnen ordenen op termen waar ik ook op kan zoeken' lagere prio dan criteria Als gebruiker wil ik kunnen zoeken op Platform, Software Type, License, Maintenance.type'

**Comment by rubenvdlinde** [comment]
Ik denk dat we hem anders moeten aanvliegen en deze lijst als enum moeten voeren op de licentie propertie (ofwel je mag geen licentie toevoegen die niet in de lijst zit) en van de ondersteunde licenties dan een referentie lijst maken.

Als we het hebben over de zoek filters zou ik alleen waarden willen tonen die daadwerkelijk voorkomen in de dataset om te voorkomen dat mensen gaan filteren op zaken waar geen één component aan voldoet.

**Comment by lencodes** [comment]
@bbrands02 om dit issue af te ronden moeten we:

1. De `array` filter bug oplossen (voor `platforms`);
2. De `licenses` endpoint data consistent maken (zie ook de comment van @rubenvdlinde hierboven over het filteren van de licenses lijst)

**Comment by matthiasoliveiro** [comment]
Issues #142 & #149 zijn voorwaardelijk voor de uitvoer van dit issue.

**Comment by rjzondervan** [comment]
Origineel 40 storypoints (20 per acceptatiecriterium)

**Comment by rjzondervan** [comment]
Origineel 40 storypoints (20 per acceptatiecriterium)

**Comment by lencodes** [comment]
Dit issue is, doordat de filtering is losgetrokken in #180, nu **alleen nog blocked door #142**

**Comment by rubenvdlinde** [comment]
@lencodes volgensmij is alleen de ordening losgetrokken in #180? niet de filtering

**Comment by rubenvdlinde** [comment]
Done
