### ISSUE TITLE
UPL weergeven op detail pagina

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#76]
"User Story  
* *Als:* APM 
* *Wil ik:* dat de relevante Uniforme Producten Lijst (UPL)  producten worden weergeven op de detail pagina
* *Zodat ik:* weet welke producten passen bij deze applicatie of component (datamodel proces etc)

Beschrijving 

Deze story beschrijft ....... 

**Geblokkeerd door:**
- [ ] #140 

 **Acceptatiecriteria:**

- [ ] Als gebruiker wil ik op de component detail pagina zien welke producten door een component worden gefaciliteerd `FE: 5`

**Comment by RonaldvCortenberghe** [comment]
Ik vraag dit nog even na, maar ik meen dat dit inderdaad was om gericht te kijken weke componentne beschikbaar zijn om een eindproducten te kunnen maken/leveren

**Comment by lencodes** [comment]
Dit issue is opgepakt voor de frontend filtering, filtering en communicatie met de backend pakken we nu dus (nog) niet op!

**Comment by vwmvanbeek** [comment]
In Den Haag hebben we de verschillende talen gekoppeld middels de verschillende standaarden. Dit is gebeurd middels de thema indeling zoals die in IRMA (https://irma.denhaag.nl/) is opgenomen. Deze indeling is ook binnen Rotterdam getoetst en heeft geleid tot een 80% match. Is via Rob Bruijnzeels gegaan. In dit model is UPL, ZTC en selectielijst aan elkaar gekoppeld, zodat deze allen zoekbaar zijn. meest recente model van GDH is opvraagbaar bij koen.bakker@denhaag.nl

**Comment by matthiasoliveiro** [comment]
`Frontend inschatting is gebaseerd op de aanname dat dit enkel data tonen op de detailpagina is (e.g. in de vorm van een tabel of iets soortgelijks).`

Dat klopt #80 gaat over het zoeken dit issue gaat over het weergeven van de UPL op het detail scherm. @RonaldvCortenberghe ik pas het issue aan zo dat het overeenkomt met de acceptatie criteria.

**Comment by bbrands02** [comment]
We willen hier een proxy instellen op https://standaarden.overheid.nl/owms/oquery/UPL-actueel.json

**Comment by lencodes** [comment]
> We willen hier een proxy instellen op https://standaarden.overheid.nl/owms/oquery/UPL-actueel.json

Vandaag een eerste opzet gemaakt voor de UPL filter, hier de volgende dingen tegengekomen waar we een oplossing voor moeten vinden:

1. Meerdere UPL's kunnen dezelfde naam hebben (e.g. "Wapenvergunning" komt driemaal voor), hierdoor kunnen we niet enkel de naam in de Select tonen (dan weet de gebruiker namelijk niet welke die selecteert);
2. De UPL lijst komt niet met unique identifiers, hierdoor moeten we deze nu zelf bijhouden in de frontend, wat niet gewenst is, dit zou beter in de Gateway opgepakt kunnen worden;


@bbrands02 Door bovenstaand kan het zijn dat we er dus niet mee wegkomen simpelweg een proxy op te zetten voor deze data.

@RonaldvCortenberghe voor nu heb ik de Grondslaglabels toegevoegd achter de namen om een unieke keuze visueel te maken (zie video). Als je hier andere ideeën bij hebt, dan hoor ik het graag!

https://user-images.githubusercontent.com/66552932/178476004-05872784-1cdb-4deb-970f-e8e0a6a60cb1.mov

**Comment by RonaldvCortenberghe** [comment]
@lencodes Hele elegante oplossing, daar kunnen we goed mee uit de voeten. Kudo's

**Comment by lencodes** [comment]
@bbrands02 om dit werkzaam te krijgen, moet de `upl` endpoint consistent data terug geven.

**Comment by matthiasoliveiro** [comment]
Issues #142 & #149 zijn voorwaardelijk voor de uitvoer van dit issue.

**Comment by rubenvdlinde** [comment]
Done
