### ISSUE TITLE
zoekresultaat component/gemeente

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#77]
"User Story  
* *Als:* APM 
* *Wil ik:* per component 1 regel als zoekresultaat met daarop meerdere gemeenten als gebruikers????????? 
* *Zodat ik:* Zodat ik direct kan zien welke gemeenten een bepaald component gebruikt en ik niet zelf hoe te beoordelen of het om het zelfde component gaat (als er per gebruikte gemeente per component één regel zou zijn) 

Beschrijving 

Deze story beschrijft ....... 

**Taken**
#130
#131

 **Acceptatiecriteria:**

- [ ] Als gebruiker wil ik in de component overzichts card een icoontje + nummer dat aangeeft hoeveel organisaties een component gebruiken
- [ ] Als gebruiker wil ik op de component detail pagina kunnen inzien welke organisaties een component gebruiken

**Comment by rubenvdlinde** [comment]
We kunnen het aantal gemeenten dat een component gebruikt weergeven in de card, maar dan wordt een card wel snel vol. Zie 
![image](https://user-images.githubusercontent.com/4021899/176285454-b3b7ac7d-b313-4b0f-aa04-743961316dc7.png)

of willen we kunnen zoeken naar gebruik binnen gemeenten (los van gemeenten als aanbiedende partij), alla 
![image](https://user-images.githubusercontent.com/4021899/176285681-58f9581a-1cc6-4077-9c76-df64ab49b8a2.png)

**Comment by vwmvanbeek** [comment]
Is het een idee om per component het eco-systeem te tonen? Dat is een combinatie van leveranciers en dienstverleners. Dat geeft een indicatie over de volwassenheid en toekomstvastheid van een component

**Comment by bbrands02** [comment]
Hier mist de koppeling naar de organisatie nog in de api

**Comment by lencodes** [comment]
@bbrands02 om deze filter werkend te krijgen hebben we een endpoint nodig om alle organisaties op te halen. Daarom assign ik 'm aan jou.

**Comment by matthiasoliveiro** [comment]
issue #130 is voorwaardelijk voor de uitvoer van dit issue.

**Comment by RonaldvCortenberghe** [comment]
akkoord
