### ISSUE TITLE
Filteren op de 5-lagen

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#78]
"User Story  
* *Als:* gebruiker
* *Wil ik:* kunnen filteren op de 5-lagen van het informatiemodel 
* *Zodat ik:* per laag kan kijken welke componenten reeds beschikbaar zijn 

Beschrijving 

Het kunnen filteren op de 5 lagen bied mij de mogelijkheid om te kijken welke DRM's  of API's er zijn om te kunnen achterhalen of die voor mij als gebruiker interessant zijn.

 **Acceptatiecriteria:**

- [ ] Als gebruiker wil ik op de zoeken pagina kunnen filteren op lagen van commonground `FE: 5`

**Comment by rubenvdlinde** [comment]
Zit deze niet al in de demo op opencatalogi.nl?

![image](https://user-images.githubusercontent.com/4021899/176285088-c06c638b-1e93-46d3-a18b-dec2211ba63f.png)

**Comment by bbrands02** [comment]
Lijkt een duplicate van #72

**Comment by rubenvdlinde** [comment]
test voor excelete

**Comment by rubenvdlinde** [comment]
Ruben van der Linde commented: test voor excelete de andere kant op

**Comment by rubenvdlinde** [comment]
Done
