### ISSUE TITLE
Template Enabler Story (maak Clone!)

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#79]
"Enabler Story  
* *Beschrijf de/het:* (techniek/model/standaard/component/infrastructuur/procedure...) 
* *van het/de:* (systeem/applicatie/omgeving/....) 
* *zodat:* (beschrijf de technische uitkomst dan wel geldende criteria van de toegevoegde eigenschap) 

Beschrijving 

Deze story beschrijft ....... 

  

_Teams ontwikkelen ook de nieuwe architectuur en infrastructuur die nodig is om nieuwe user stories te kunnen implementeren. In deze gevallen raakt de story geen eindgebruiker direct. Teams gebruiken 'enabler stories' om de verkenningsfase, architectuur of infrastructuur te ondersteunen. Enabler-verhalen kunnen worden uitgedrukt in technische in plaats van gebruikersgerichte taal_

Gedetailleerde beschrijving van de technische uitkomst dan wel geldende criteria van de toegevoegde eigenschap. 

De acceptatiecriteria biedt de informatie die nodig is om ervoor te zorgen dat de story correct wordt geïmplementeerd en omvat de relevante functionele en NFR's. 

"

**Comment by RonaldvCortenberghe** [comment]
Kan weg , was een template in Jira

**Comment by RonaldvCortenberghe** [comment]
Was een template in Jira
