### ISSUE TITLE
Als portfoliomanager/informatieadviseur/architect wil ik dat de beschikbare CG componenten op een praktisch wijze in de catalogus zijn ontsloten, zodat ik deze zelf kan downloaden bij de bron of kan aanvragen bij de component eigenaar.

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#82]
"Als portfoliomanager/informatieadviseur/architect wil ik dat de beschikbare CG componenten op een praktisch wijze in de catalogus zijn ontsloten, zodat ik deze zelf kan downloaden bij de bron of kan aanvragen bij de component eigenaar. 

Alle modellen kunnen worden gedownload, voor datasets geldt het principe bevragen bij de bron 

Met OpenCatalogi is het delen en integreren van alle onderdelen in de catalogus mogelijk

Downloaden: 
- De Bronnen zitten niet in de OpenCatalogi. Dus moet er een verwijzing naar de bronnen zijn zodat men via de Opencatalogi bij de bron kan komen en daar downloaden #52

~~Federeren:~~
~~- clonen catalogi items~~

Doorverwijzen: 
- verwijzingen anders dan bronsystemen #43 
- informatie over beheerpartijen" #45

**User stories**

- [x] #45
- [x] #43
- [x] #52

**Acceptatie criteria**

- [x] We verwachten een detail pagina waar je een download kan starten of doorverwezen wordt naar de bron (onderwerp kan applicaties, componenten, Object definite, modellen oid zijn.)

**Comment by rubenvdlinde** [comment]
Er zijn hier drie voorbeelden van

1. data.overheid verwijst vanuit cards direct door naar externe bronnen (bijvoorbeeld vanaf https://developer.overheid.nl/repositories?technologie=34&pagina=6)
2. data.overheid heeft voor api's een detail pagina waarvandaan ze doorverwijzen (https://developer.overheid.nl/apis/00000001802327497000-kadaster-bag-current) 
3. De commonground catalogus geeft een overlay vanaf waar ze doorverwijst (https://componentencatalogus.commonground.nl/componenten/195?) 

Mijn persoonlijke voorkeur gaat uit naar een detail pagina omdat we naast doorverwijzen ook verbanden met andere componenten, applicaties etc inzichtenlijk willen maken.

**Comment by matthiasoliveiro** [comment]
Er zijn maar 2 mogelijkheden:

- Downloaden
- Doorverwijzen

Federeren gebeurt op de achtergrond en is niet zichtbaar.
