### ISSUE TITLE
Visualiseren van zoekresultaten en overzichten.

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#83]
"Als portfoliomanager/informatieadviseur/architect wil ik overzichten kunnen genereren van  alle CG componenten die binnen en buiten de gemeente beschikbaar zijn waarbij oa de samenhang binnen het 5-lagenmodel wordt gevisualiseerd, zodat ik het overzicht behoud in samenhang en functie van de verschillende componenten, modellen en documentatie. 

OpenCatalogi heeft een visualisatiefunctionaliteit voor zowel het gemeentelijke overzicht als het totaaloverzicht, waarmee verschillende onderdelen door alle lagen heen in overzichten worden getoond. Bijvoorbeeld contextdiagrammen 

Deze epic is bedoeld om de visualisatie van resultaten 

- De onderlinge samenhang tussen de componenten (ook over de verschillende lagen) moet visueel inzichtelijk zijn 
- Presenteren in een mooi formaat in diverse dwarsdoorsneden (bijv. type portfolio, doelgroep, per laag) 
- Visualisaties opbouwen op basis van autorisaties (bijv. zichtbaar maken van contactgegevens)"

**User stories** 

- [x] #54 
- [x] #56 
- [x] #57 
- [x] #59

**Comment by rubenvdlinde** [comment]
Ik zou contact gegevens buiten de visualisaties laten en die op de component detail pagina tonen.

Dit is hoe het nu in de componenten catalogus wordt weergegeven

![image](https://user-images.githubusercontent.com/4021899/176276915-b3252526-0c22-4c92-b326-e1a5ed985330.png)

developer.overheid api's

![image](https://user-images.githubusercontent.com/4021899/176277057-e55e847c-6fe1-422a-9fc1-517cada0aebe.png)

developer.overheid repo's

![image](https://user-images.githubusercontent.com/4021899/176277221-95246e0f-7deb-4036-8698-d3114bc39e3b.png)

**Comment by RvdKlip** [comment]
Visualiseren gaat niet in tabellen en lijstjes. Neem bijvoorbeeld https://rotterdam.horizzon.cloud/home

**Comment by RvdKlip** [comment]
Onderstaand om aan te geven welk type visualisaties handig zijn

![Knipsel](https://user-images.githubusercontent.com/38490649/176650637-7d773d6b-f4b1-4cad-8f26-b5efb4ded4db.PNG)
![Knipsel2](https://user-images.githubusercontent.com/38490649/176650737-081c971d-1b93-4215-8ecf-e0d6ca4e812d.PNG)
![Knipsel4](https://user-images.githubusercontent.com/38490649/176650805-dd18e7ef-1c80-47e2-aa7b-abe3b829494f.PNG)
![Knipsel5](https://user-images.githubusercontent.com/38490649/176650931-4880ccd7-933d-480d-a3d8-f78c968de7b9.PNG)
![Knipsel6](https://user-images.githubusercontent.com/38490649/176650956-9aec99b5-0c33-4ac2-87d1-13a7ca07fc87.PNG)
![Knipsel7](https://user-images.githubusercontent.com/38490649/176650969-6dbe563f-ae44-4ec5-b63d-a0b3bb1b6ee9.PNG)

**Comment by vwmvanbeek** [comment]
Is het een idee om hier designers naar te laten kijken? Juist UX designers zorgen voor een toegankelijk design waar gebruikers snel hun weg vinden naar wat ze zoeken. Ik vind het lastig om vanuit de losse stories de samenhang te zien, dus mogelijk dat enkele van mijn opmerkingen irrelevant zijn, omdat elders een overal plan is voor indeling en toegangspaden (kan opgesteld worden middels UX-research en vervolgens UX design
