### ISSUE TITLE
Als componenteigenaar wil ik CG componenten, modellen en documentatie kunnen classificeren en categoriseren , zodat ik met het opnemen van deze objecten in de catalogus de onderlinge samenhang kan borgen en presenteren naar eindgebruikers.

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#84]
"Als componenteigenaar wil ik CG componenten, modellen en documentatie kunnen classificeren en categoriseren , zodat ik met het opnemen van deze objecten in de catalogus de onderlinge samenhang kan borgen en presenteren naar eindgebruikers. 

Het additioneel kunnen metadateren van objecten is belangrijk om bijvoorbeeld het onderscheid tussen open data en beschermde data te kunnen aangeven 

Het indexeren van externe bronnen 

Gegevens kunnen worden gegroepeerd  

Gegevens kunnen verwijzingen bevatten 

Metadateren: 
- Elk object moet uniek te vinden zijn 
- Elk object moet een naam hebben en tot een bepaald laag behoren 
- Samenhang tussen objecten moet aangegeven kunnen worden 
- Vastlegging Gemma-kenmerken per component 

Indexeren: 
- Nieuwe initiatieven handmatig opvoeren, bestaande initiatieven live ophalen uit systemen 
- Aansluiting op externe bronnen waarin componenten zijn gedefinieerd of worden gebruikt 
- Indexeren van relaties tussen componenten 
- Signaleringsfunctie bij dubbele componenten 

Groeperen: 

Doorverwijzen: 
- De catalogus bevat niet alle info die in de bronsystemen zitten, dus moet er een verwijzing naar een bronsysteem zijn. 
- Eventuele beheerpartijen moeten benaderd kunnen worden, dus die gegevens moeten bekend zijn. 

**User stories**

- [x] #63 
- [x] #61 
- [x] #69 
- [ ] #70 
- [x] #64 
- [x] #60 
- [x] #58 
- [x] #55 
- [ ] #53

**Comment by lencodes** [comment]
Zie https://github.com/OpenCatalogi/.github/issues/14#issuecomment-1184151484 voor een onderliggende vraag in deze Epic.
