### ISSUE TITLE
Template User story (maak Clone!)

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#86]
"User Story  
* *Als:*  
* *Wil ik:*  
* *Zodat ik:*  

Beschrijving 

Deze story beschrijft ....... 

  

_Een User Story is een korte, eenvoudige beschrijving van een behoefte van de eindgebruiker. Een kort verhaaltje, geschreven vanuit het oogpunt van die eindgebruiker.  Een User Story is geen functionele beschrijving, maar maakt duidelijk wat een eindgebruiker wil, of nodig heeft en ook waarom dat nodig is_

Gegeven: (beschrijving van de uitgangssituatie) 
Als: (beschrijving van de actie) 
Dan: (beschrijving van de eindsituatie die nog acceptabel is) 

De acceptatiecriteria biedt de informatie die nodig is om ervoor te zorgen dat de story correct wordt geïmplementeerd en omvat de relevante functionele en NFR's. 

"

**Comment by RonaldvCortenberghe** [comment]
Volgens mij kan deze weg, als we een soort van sjabloon/template hebben voor een userstory
