### ISSUE TITLE
Als portfoliomanager/informatieadviseur/architect wil ik kunnen zoeken naar alle CG componenten die binnen en buiten de gemeente beschikbaar zijn waarbij de samenhang binnen het 5-lagenmodel wordt gepresenteerd

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#87]
"Als portfoliomanager/informatieadviseur/architect wil ik kunnen zoeken naar alle CG componenten die binnen en buiten de gemeente beschikbaar zijn waarbij de samenhang binnen het 5-lagenmodel wordt gepresenteerd in de zoekresultaten, zodat ik mijn beslissingen rondom informatievraagstukken en ontwikkeling hiermee kan onderbouwen 

OpenCatalogi valt of staat met een volwassen zoekfunctionalteit. Het is mogelijk dat deze functie door een ander component dan binnen OpenCatalogi wordt gerealiseerd. Naadloze integratie is in dit geval wel een vereiste.

Zoeken: 
- Er moet gezocht kunnen worden op (bepaalde) termen (tags?) 
- Er moet gezocht kunnen worden per laag maar ook over alle lagen heen 
- Er moet gezocht kunnen worden op functionaliteit en/of bedrijfsfuncties 
- Er moet gezocht kunnen worden naar bepaalde gemeenten (typering gemeente). 

Filteren: 
- Het moet mogelijk zijn om bepaalde soorten gegeven te zoeken. 
- Het moet mogelijk zijn om van bepaalde organisaties objecten te zoeken"

**User stories**

- [x] #76
- [x] #80
- [x] #71 
- [x] #73 
- [x] #74 
- [x] #75 
- [x] #72
- [x] #77

**Comment by vwmvanbeek** [comment]
Als ProductOwner binnen Common Ground zou ik graag willen kunnen zoeken op:

- per domein/thema (parkeren, Belastingzaken, Erfpacht, enz) aanvullend met filtering naar laag van de 5 laags
- of op de datalaag reeds een data standaard voor producten is gedefinieerd voor een domein/thema
- beschikbare Gemma componenten
- oplossingen en componenten die door >1 leveranciers wordt ondersteund
- oplossingen en componenten die door >x dienstverleners wordt afgenomen 
- oplossingen en componenten die ook door dienstverleners/organisaties (profit) worden afgenomen, die geen gemeente zijn

**Comment by RonaldvCortenberghe** [comment]
Afgerond
