### ISSUE TITLE
Als gebruiker wil ik externe bronnen kunnen indexeren

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#9]
Uitvraag *Het indexeren van externe bronnen*

Kernvraag onder deze functionaliteit is welke bronnen, aangezien dat een discussiepunt is met een aantal mogelijke oplossingen is die keuze ondergebracht in een separate  [discussie](https://github.com/OpenCatalogi/.github/discussions/11).

**Comment by matthiasoliveiro** [comment]
Huidige afspraak is: huidige componenten catalogus

**Comment by rubenvdlinde** [comment]
Op 28 Jun heeft de PO een bredere keuze gemaakt onder de hier verwezen discussie. Dan is het wel goed om hier even te realiseren dat de scope wordt verkleind.

**Comment by rjzondervan** [comment]
Dit zou met het oplossen van issue #41 mee moeten komen.

**Comment by RonaldvCortenberghe** [comment]
doone
