### ISSUE TITLE
Als gemeente wil ik een voorwaarde lijst voor componenten kunnen opstellen

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#92]
### Project Location

Frontend

### Is your feature request related to a problem? Please describe

Ja, nu weet ik als gemeente niet of componenten wel of niet voldoen aan mijn minimale eisen voor een component. e.g. wasstraat etc. 

### Describe the solution you'd like

Op organisatie niveau voorwaarden voor componenten kunnen opstellen, zo als:
- licentie
- productie waarden
- minimum aantal beheerspartijen
- pentest/dpia
- unit test
- Open Source
- Technieken uitsluiten (bijvoorbeeld postgress)

Etc

### Describe alternatives you've considered

Als gemeente zelf een wasstraat organiseren om te bepalen of een component productie waardig is

### Additional context

Dit helpt gemeenten om keuzes te maken voor componenten

Acceptatie criteria
- [ ] Rating is zichtbaar op de component detail pagina
- [ ] Rating details zijn zichtbaar
- [ ] Ratings kunnen worden gedaan op basis van de publiccode
- [ ] Uitleg van de rating toevoegen aan about pagina

**Comment by rubenvdlinde** [comment]
@lencodes de oorspronkelijke afspraak met @RonaldvCortenberghe was niet een heel rating systeem (wat verwarrend is  tussen gemeenten) maar simpel weg het tonen van een warning bij componenten die niet aan de voorwaarden van de gemeente voldoen. 

Het getoonde voorbeeld is daarmee out  of scope.

**Comment by JeroenGRotterdam** [comment]
Alleen eindresultaat rating tonen op detail pagina. In about pagina uitleg opbouw rating.

**Comment by JeroenGRotterdam** [comment]
onderstaande lijstje aanwezig/afwezig scoren:
licentie
productie waarden
minimum aantal beheerspartijen
pentest/dpia
unit test
Open Source
Technieken uitsluiten (bijvoorbeeld postgress)

**Comment by rubenvdlinde** [comment]
Dit issue ging over een voorwaarde lijst, ofwel is iets voor mijn als gemeente acceptabel aan de hand van mijn architectuur eisen. 

Niet over een rating als in hoeveel punten scoort een component (dat zou een volledig los issue zijn). Ik zie wel dat iemand de acceptatie criteria heeft aangepast om het over een rating te hebben, dat zal de verwarring vermoedelijk hebben veroorzaakt.

**Comment by rjzondervan** [comment]
> Dit issue ging over een voorwaarde lijst, ofwel is iets voor mijn als gemeente acceptabel aan de hand van mijn architectuur eisen.
> 
> Niet over een rating als in hoeveel punten scoort een component (dat zou een volledig los issue zijn). Ik zie wel dat iemand de acceptatie criteria heeft aangepast om het over een rating te hebben, dat zal de verwarring vermoedelijk hebben veroorzaakt.

Bovenstaande wordt opgepakt in een nieuw, nader te refinen issue.
