### ISSUE TITLE
Als eindgebruiker van OpenCatalogi wil ik een heldere definitie van Applicaties en Componenten, zodat...

### ISSUE THREAD

**Issue by RvdKlip** [OpenCatalogi/.github#93]
...ik de inhoud in OpenCatalogi op een begrijpelijke en juiste wijze kan interpreteren.

**Toelichting**
De OpenCatalogi biedt inzicht in 'componenten' in de verschillende lagen. Met betrekking tot definities moeten we in ieder geval de term 'component' en de term 'applicatie' vanuit het perspectief van de catalogus afdekken:  
- Applicatie
- Component
Er spelen ook termen als 'Proces' en '()Model' als invulling van een component, waardoor een invulling per laag ontstaat. 

Definities kunnen we vastleggen op bijvoorbeeld een 'about' pagina in open catalogi. 

Zie ook #88 

Acceptatie criteria:

- [x] Onderstaande definities worden weergegeven op een about pagina in opencatalogi (zit in het hoofdmenu)

**Comment by RvdKlip** [comment]
Hierbij een eerste aanzet (uw kritische bijdrage is gewenst). 

Opencatalogi is een weergave van Componenten verdeeld over de 5 lagen zoals gedefinieerd door VNG in het Gegevenslandschap (https://www.gemmaonline.nl/index.php/Gegevenslandschap en https://componentencatalogus.commonground.nl/5-lagen-model).

**Component**
Voor OpenCatalogi hanteren we deze archimate definitie _met de aanscherpingen_ die vanuit de VNG worden meegegeven in hoofdstuk 2.1 van https://www.gemmaonline.nl/images/gemmaonline/0/09/GEMMA_Gegevenslandschap_-_Informatiearchitectuurprincipes_v1_0.pdf.

De archimate definitie: 
Een modulair, zelfstandig inzetbaar, herbruikbaar en vervangbaar deel van een systeem, dat zijn functionaliteit aanbiedt via goed gedefinieerde interfaces. Applicatiecomponenten stellen functionaliteit beschikbaar, die gebruikt wordt om de applicatiediensten mee te leveren. 

De aanscherpingen vanuit de VNG: 
We werken met componenten die **afgebakende functionaliteit** kennen, **zoveel mogelijk ontkoppeld** zijn en met 
elkaar communiceren via **gestandaardiseerde interfaces**:

Ingevuld door (voor zover van toepassing voor OpenCatalogi):
Gangbare service-oriëntatie
- Autonomie - Componenten zijn zelfstandig inzetbaar, schaalbaar en vervangbaar.
- Losse koppeling - Componenten zijn onderling onafhankelijk en zelfstandig door te ontwikkelen en gebruiken. 
- Herbruikbaar - Componenten zijn vaker in te zetten door ze in verschillende omgevingen te gebruiken of door 
- een component vaker te instantiëren binnen één omgeving.
- Samenstelbaar - Componenten kunnen worden gecombineerd tot nieuwe componenten. 
- Abstractie - Afnemers hoeven alleen de functionaliteit van een component te kennen en niet de interne 
- werking ervan. 
- Service-contract - Een component kent duidelijke voorwaarden en leveringsafspraken over de kwaliteit en het 
- volume van mogelijk gebruik door afnemers.
- Vindbaar - Services zijn voorzien van metadata en zijn goed vindbaar.
- Toestandsloos - Componenten die diensten leveren bewaren geen statusinformatie (maar laten dit over aan 
- afnemers of gespecialiseerde componenten).
...
Componenten conformeren zich aan het vijf-lagenmodel
a. Componenten beperken zich tot functionaliteit binnen de laag waartoe ze behoren 
b. Componenten voor interactie- en procesfunctionaliteit vragen gegevens op bij de bron via 
gestandaardiseerde interfaces.
c. Componenten bewerken geen brongegevens anders dan bij de bron 
...

**Comment by RonaldvCortenberghe** [comment]
Is het een idee om de Definities als aparte discussie op te zetten zodat een ieder zijn commentaar er op kan geven en we uiteindelijk (op een aangegeven en nog vast te stellen einddatum, zodat we planningtechnisch geen risico lopen) een definitie vaststellen?

**Comment by matthiasoliveiro** [comment]
> Is het een idee om de Definities als aparte discussie op te zetten zodat een ieder zijn commentaar er op kan geven en we uiteindelijk (op een aangegeven en nog vast te stellen einddatum, zodat we planningtechnisch geen risico lopen) een definitie vaststellen?

Ja dat lijkt me een goed idee! dan gebruiken we dit issue voor de uitvoering er van.
We moeten hier wel acceptatie criteria bij vast leggen.

**Comment by RonaldvCortenberghe** [comment]
Allen,

Ik heb discussies aangemaakt, omdat anders we een discussie in dit issue krijgen. Graag discussie in de discussie voeren. Omdat we nog acceptatiecriteria moeten toevoegen staat deze nog open

**Comment by RonaldvCortenberghe** [comment]
Definities worden vastgelegd in een about pagina in OpenCatalogi

**Comment by lencodes** [comment]
Pagina is beschikbaar op https://opencatalogi.nl/about. 

Aanpassingen, toevoegen of ander werk aan deze pagina mag in een nieuw issue vastgelegd worden.

**Comment by RonaldvCortenberghe** [comment]
Discussie gesloten documentatie pagina aangemaakt
