### ISSUE TITLE
Als leverancier wil ik kunnen aangeven welke componenten ik ondersteun 

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#95]
Voortzetting van probleem gevonden onder #42 

### Project Location

Frontend

### Is your feature request related to a problem? Please describe

Nu kan alleen het component zelf bepalen welke leveranciers ondersteuning bieden, maar in open source gaan de leveranciers daar feitelijk zelf over en de componenten.

### Describe the solution you'd like

Ik wil als leverancier kunnen inloggen, mijn gegevens bewerken en aangeven welke componenten ik ondersteun.

Om het geheel iets makkelijker te maken ben ik dan als leverancier een organisatie

### Describe alternatives you've considered

Melden van support via het component zelf (as is)

### Additional context

PublicCode.yaml ondersteund dit niet, maar feitelijk valt het daar ook buiten (public code beschrijft alleen het systeem van software informatie niet het ecosysteem daar omheen).

**Comment by rubenvdlinde** [comment]
@lencodes  Het is open sourcee dus iedereen mag ondersteuning aanbieden op alles. Dat  zit ingebakken in het licentie model.

**Comment by JeroenGRotterdam** [comment]
Invulling van deze story is het organisatie object. Moet verder uitwerkt worden

**Comment by JeroenGRotterdam** [comment]
Deze story heeft mogelijk veel implicaties tav toegangsrechten externe partijen, extra schermen etc dus moet verder refined worden. mogelijk niet MVP.

**Comment by rubenvdlinde** [comment]
Refinnen aan de hand van demo op 6-10
